### ISSUE TITLE
develop Contributing Guide

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#102]
As part of incubation we need to clarify contributions to PyWPS.  Task list:

- [x] clarify with OSGeo Incubation Committee what level of contribution agreements are required
- [x] add a `.github/CONTRIBUTING.md` file to PyWPS source code repo (example: https://github.com/geopython/pycsw/blob/master/CONTRIBUTING.rst)
- [x] if required, update `.github/PULL_REQUEST_TEMPLATE.md` with contribution agreement

**Comment by jachym** [comment]
Used PyCSW templates - should be fine for OSGeo
