### ISSUE TITLE
fix safe file handling in unit tests

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#109]
# Description

Unit tests in a Python 3 environment yield `ResourceWarning` warnings like:

```
/home/travis/build/geopython/pywps/tests/test_inout.py:64: ResourceWarning: unclosed file <_io.FileIO name='/tmp/tmpwbpvbq0c' mode='rb'>
```

# Environment

- operating system: Ubuntu
- Python version: 3.4
- PyWPS version: master
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): unit test runner

# Steps to Reproduce

```bash
# in a Python 3 virtualenv
python -m unittest tests
```
# Additional Information

Initial discussion in #106.

Example can be found in current travis builds: https://travis-ci.org/geopython/pywps/jobs/111190874#L360

**Comment by mishravikas** [comment]
Can I take this bug?

**Comment by tomkralidis** [comment]
Sounds good @mishravikas!

**Comment by jachym** [comment]
@mishravikas go for it, but I'm not sure it's easy to be fixed. Have a look in it and in case, you are not sure how to approach, just move on with your tasks

**Comment by ldesousa** [comment]
Line 160 in inout/basic.py, in the method get_stream() save a reference to the file object. CLose this file object after the handler is called - Process class, _run_process() method.

**Comment by jachym** [comment]
https://docs.python.org/3/reference/datamodel.html __del__ object destroyer should do it

**Comment by jachym** [comment]
#175 fixes this
