### ISSUE TITLE
add PyWPS to UbuntuGIS

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#114]
cc @kalxas, @khosrow, @mipilon

# Description

Add PyWPS latest stable to UbuntuGIS lifecycle.

# Additional Information

Initial progress: https://launchpad.net/~gcpp-kalxas/+archive/ubuntu/osgeolive/+packages

**Comment by kalxas** [comment]
I will include this new package in OSGeoLive ppa, so it will find its way to UbuntuGIS when 9.5 is released

**Comment by tomkralidis** [comment]
@kalxas any update on this one?

**Comment by kalxas** [comment]
https://launchpad.net/~ubuntugis/+archive/ubuntu/ubuntugis-testing/+sourcepub/6503469/+listing-archive-extra
