### ISSUE TITLE
add PyWPS to OSGeo Live

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#119]
cc @kalxas 
# Description

Add PyWPS to the OSGeo Live project.  Requirements:
- implementation/packaging/setup script(s)/configuration(s)
- documentation (overview, quickstart)

# Environment

- operating system:
- Python version:
- PyWPS version:
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [x] other (please specify): OSGeo Live
- web server
 - [x] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
NA
# Additional Information

Related issue #114, we can start with 3.x and move towards 4.0.0 when final/stable.

Initial implementation:

- overview: https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/overview/pywps_overview.rst
- quickstart: https://github.com/OSGeo/OSGeoLive-doc/blob/master/en/quickstart/pywps_quickstart.rst
- project logo: https://github.com/OSGeo/OSGeoLive-doc/blob/master/images/project_logos/logo-pywps.png
- test installation: https://github.com/OSGeo/OSGeoLive/blob/master/bin/labs/install_pywps.sh

**Comment by kalxas** [comment]
You will need to apply as per:
https://wiki.osgeo.org/wiki/Live_GIS_Disc#How_to_add_a_project_to_OSGeoLive

**Comment by tomkralidis** [comment]
thanks @kalxas first draft at https://github.com/geopython/pywps/wiki/OSGeoLiveApplication.  Once we finalize this, we will send as email.

**Comment by kalxas** [comment]
looks good

**Comment by tomkralidis** [comment]
Application submitted: https://lists.osgeo.org/pipermail/live-demo/2016-May/011137.html

**Comment by tomkralidis** [comment]
Application accepted: http://osgeo-org.1560.x6.nabble.com/PyWPS-application-td5266204.html

Installation pull request: https://github.com/OSGeo/OSGeoLive/pull/112
Docs pull request: https://github.com/OSGeo/OSGeoLive-doc/pull/127
