### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by jachym** [geopython/pywps#122]
# Description

Write user (and contributor?) documentation for master (pywps-4) branch

# Environment

- operating system: All
- Python version: All
- PyWPS version: Master (4.0.0)
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

Documentation will be propagated to http://pywps.readthedocs.org/en/latest/

**Comment by ldesousa** [comment]
There are still a number of sections in the docs that do not have any text at all.

**Comment by jachym** [comment]
I'm on this task right now, because of the FOSS4G-Workshop

**Comment by jachym** [comment]
it's release-able for now, closing
