### ISSUE TITLE
request.inputs['input_name'] returns deque

### ISSUE THREAD

**Issue by pka** [geopython/pywps#128]
# Description

Accessing a request input with `request.inputs['data_input'].data` as in the [documentation](/geopython/pywps/blob/master/docs/process.rst#reading-input) throws an exception because `request.inputs['input_name']` returns a deque. Reading the [tests](/geopython/pywps/blob/master/tests/test_wpsrequest.py#L54), I'm not sure whether documentation or implementation is wrong.

# Environment

- operating system: Linux
- Python version: 2.7.6
- PyWPS version: a896d3662b
- source/distribution
 - [x] git clone
 - [x] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [x] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by jachym** [comment]
@pka please, where is the code you are referring to, I would like to fix it 

it should be request.inputs['data_input'][0].data - it's always assumed, there could be multiple input values of the same identifier
