### ISSUE TITLE
StoreExecuteResponse returning invalid StatusLocation URLs

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps#137]
The _ExecuteResponse_ document to an _Execute_ request with the _StoreExecuteResponse_ flag set **true** is returning an invalid _StatusLocation_, e.g.:

`
<wps:ExecuteResponse xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_response.xsd" service="WPS" version="1.0.0" xml:lang="en-US" serviceInstance="http://localhost/pywps?service=WPS&request=GetCapabilities" statusLocation="/wps/outputs/a33a9392-3944-11e6-abe1-00215df3520e.xml">`

In this case, the URL: 
`http://localhost:5001/wps/outputs/a33a9392-3944-11e6-abe1-00215df3520e.xml` 
actually does not exist.

**Comment by jachym** [comment]
To stress this: that is the problem of flask application - apache works 

we (I have) have broken flask pywps-demo - we shall fix that by adding support for more configuration file

IMHO demo.py should be cleaned a lot, based also on the work done be @jan rudulf in GSoC

**Comment by jachym** [comment]
works on flask

shall be confirmed on apache

**Comment by ldesousa** [comment]
Right now this is not working with flask. This request:

http://localhost:5000/wps?REQUEST=Execute&SERVICE=WPS&VERSION=1.0.0&IDENTIFIER=ultimate_question&STORE_EXECUTE_RESPONSE=true&STATUS=true

Returns this response:


<wps:ExecuteResponse xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 http://schemas.opengis.net/wps/1.0.0/wpsExecute_response.xsd" service="WPS" version="1.0.0" xml:lang="en-US" serviceInstance="http://localhost/wps?service=WPS&request=GetCapabilities" statusLocation="/data/be70a8f2-6c36-11e6-9916-183da2beac62.xml"><wps:Process wps:processVersion="1.3.3.7"><ows:Identifier>ultimate_question</ows:Identifier><ows:Title>Answer to the ultimate question</ows:Title><ows:Abstract>This process gives the answer to the ultimate question of "What is the meaning of life?</ows:Abstract></wps:Process><wps:Status creationTime="2016-08-27T11:15:06Z"><wps:ProcessSucceeded>PyWPS Process finished</wps:ProcessSucceeded></wps:Status><wps:ProcessOutputs><wps:Output><ows:Identifier>answer</ows:Identifier><ows:Title>Answer to Ultimate Question</ows:Title><wps:Data><wps:LiteralData dataType="urn:ogc:def:dataType:OGC:1.1:string">42</wps:LiteralData></wps:Data></wps:Output></wps:ProcessOutputs></wps:ExecuteResponse>

**Comment by ldesousa** [comment]
After setting up configuration correctly, and using the latest version of pywps-demo, it was possible to successfully test the StatusLocation with Flask and Apache.

Apache needs a bit more detailed configuration (issue #166).
