### ISSUE TITLE
How to preserve filenames of complex outputs?

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#153]
... another question i would like to ask for a long time :)

When you return a complex output as reference you end up with a URL ending with a filename like `output-123456.nc` (at least with pywps 3.x). Technically that's fine but people like to preserve their own filenames like `temperature_eur_2011.nc`. A workaround would be to return the url as a string parameter, but one looses the mime-type then. A quick fix could be to generate an output folder with a uuid name and put all the output files in it with the user/process defined names.

Another topic is when you have multiple files for a single complex output parameter. The WPS api allows only a single reference. A workaround (used for example in COWS) is to return an xml or json document with all the references to the output files. But it would be nice if this result document would follow a common standard (maybe recognisable by a mime-type?).

Any thoughts on this?

Cheers,
Carsten

**Comment by jachym** [comment]
well, I like both ideas
the second could be implemented with help of OGC OWS (WCS/WFS) outputs IMHO

I'm adding this to our future versions - I like especially the idea with uuid folder names

**Comment by cehbrecht** [comment]
PR #258 keeps output filenames and uses folders with uuid.

**Comment by ldesousa** [comment]
Fixed in PR #258
