### ISSUE TITLE
Taging pywps-demo along with pywps-core

### ISSUE THREAD

**Issue by jachym** [geopython/pywps#160]
# Description

Make sure and write documentation, that pywps-demo and pywps are in line and released in the same day.

**Comment by ldesousa** [comment]
After some research I have at two proposals to address this issue:

### 1. Include `pywps` as a [submodule](https://git-scm.com/book/en/v2/Git-Tools-Submodules) in `pywps-demo`
This option automatically obliges each `pywps-demo` commit to reference a specific `pywps` commit. Both projects become hard-wires, so to say, there is always a formal way of tracking with which version of the core library the demo was tested.
The first downside to this option is an increase in complexity and management activities. In second place it modifies the install procedure: the user clones only the `pywps-demo` project (using the `recursive` directive) then access the `pywps-demo/pywps` folder and runs `setup.py install` from there. This is less elegant than the process we have right now.

### 2. Leave the projects as they are and tag both manually
This means that each a new tag is created on the `pywps` project, a similar tag must be created in `pywps-demo`. This is easier to do, but the projects are not hard-wired and synchronisation must rely entirely on humans. Even the install remains as before, some hiccups are to expect.

In sum, there is no perfect choice. Personally, I am more inclined for option 2, but would like to hear your opinions before closing this issue.

**Comment by tomkralidis** [comment]
+1 for option 2

**Comment by jachym** [comment]
+1 for option 2, I'm manual guy: give me clear step-by-step description what to do while releasing and I'll do it. If there will be "create tag to pywps-demo", I'll do it

**Comment by jorgejesus** [comment]
+1 for option 2

**Comment by jonas-eberle** [comment]
+1 for option 2

**Comment by ldesousa** [comment]
Option 2 it is. Something more to add to the developer guidelines.

**Comment by jachym** [comment]
+1 for option 2 

Just Readme has to be updated
