### ISSUE TITLE
Uncomplete execute resonse

### ISSUE THREAD

**Issue by jachym** [geopython/pywps#178]
# Description

# Environment
- operating system:
linux

- Python version:
2/3

- PyWPS version:
 rc2

- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): 

flask

# Steps to Reproduce
```
python demo.py
wget -O - --content-on-error --post-file static/requests/execute_buffer_post.xml  http://localhost:5000/wps
```

ressult: there are no Outputs in the response

# Additional Information
it's due to unproperly evaluated condition

https://github.com/geopython/pywps/blob/master/pywps/app/Process.py#L245

percent_done is excactly 100 in this case -> outputs would not get generated 

previously: status was generated twice, maybe the "fix" introduced this issue

**Comment by jonas-eberle** [comment]
Maybe we can just remove the if clause and always execute the status update?
`wps_response.update_status('PyWPS Process finished', 100, STATUS.DONE_STATUS, clean=self.async)`

**Comment by jachym** [comment]
@jonas-eberle yah, that would be my first atempt .. and test asynchronous and synchronous processes heavily (anyway)
