### ISSUE TITLE
version convention fails Debian packaging

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#185]
cc @jachym 
# Description

When assembling Debian packaging, the version `4.0.0rc2` is causing error:

```
W: python-pywps: rc-version-greater-than-expected-version 4.0.0rc2 > 4.0.0 (consider using 4.0.0~rc2)
```
# Environment
- operating system: Debian 8
- Python version: 2.7.0
- PyWPS version:
- source/distribution
  - [x] git clone
  - [ ] Debian
  - [ ] PyPI
  - [ ] zip/tar.gz
  - [ ] other (please specify): 
- web server
  - [ ] Apache/mod_wsgi
  - [ ] CGI
  - [ ] other (please specify): 
# Steps to Reproduce

As per https://github.com/geopython/pywps/wiki/ReleasePackaging#debian-packaging
# Additional Information

Changing the version number to `4.0.0-rc2` fixes the issues.

**Comment by tomkralidis** [comment]
Debian version policy: https://www.debian.org/doc/debian-policy/ch-controlfields.html#s-f-Version

**Comment by jachym** [comment]
Do I understand correctly, that  4.0.0~rc3 should work? To VERSION.txt file? 

I was approaching the https://www.python.org/dev/peps/pep-0440/#pre-releases spec, which says

X.YaN   # Alpha release
X.YbN   # Beta release
X.YrcN  # Release Candidate
X.Y     # Final release

and I was facing some troubles at readthedoc and setup.py

ok, let's stick to debian and try to get over it in python env, I'll do it for rc3, ok?

**Comment by jachym** [comment]
Hi @tomkralidis , will https://github.com/geopython/pywps/pull/210 be ok for you? 

@ldesousa it covers the pywps-demo topic somehow too - are you ok with that?

**Comment by tomkralidis** [comment]
Thinking more about this, perhaps we should only update debian versioning for FINAL releases (and not alpha/beta/rc) given only stable/final releases should really be package candidates.  Thoughts?

**Comment by tomkralidis** [comment]
(continued)

...this way, we'll never run into Debian packaging issues when tagging non-final versions.

**Comment by jachym** [comment]
That makes sense to me - but, that leads us back to original issue :-)

X.YrcN - Python way

or

X.Y~rcN - Debian way

?

**Comment by tomkralidis** [comment]
IMHO X.Y.Z[-[alpha|beta|rc]].
