### ISSUE TITLE
clarify Templating code attribution

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#186]
# Description

From @jorgejesus 

> If I am not mistaken (@jachym knows better) I think the Template
structure on pywps3.2 is based on this external library (GNU GPL)
>
> http://htmltmpl.sourceforge.net/python-api.html
>
> That was then ported into inside the pywps code.

**Comment by jachym** [comment]
Beacuse of HUMBOLDT http://www.esdi-humboldt.eu/home.html project and license issues, I have re-implemented the templating mechanism for PyWPS by myself https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Template.py - there is no dependency, everything is internal.
