### ISSUE TITLE
Add copyright headers to all files

### ISSUE THREAD

**Issue by jachym** [geopython/pywps#187]
Add Copyright headers

- [x] pywps-3.2 (GNU/GPL)
- [x] pywps-master (MIT)

**Comment by jorgejesus** [comment]
On my branch I have commited the files with the licenses. I am have used the MIT on python-master with the following:

Copyright (C) 2014-2016 PyWPS Development Team, represented by
PyWPS Project Steering Committee

1) I am not certain if it should be represented by PyWPS Project Steering Committe or just @jachym. I prefer the first

2) Where I found the authors name (mainly @mgax  @Noctalin ) I have included them on __author__, I thinking to put a table on line and ask for people to fill it to clain authorship of code

3) The code needs to be passed by flake8 at least to check if modules are being used, already noticed some declared modules that are not used

Pull request: I would do it after I pass everything through flake8, @jachym  are all the points above OK with you ???

**Comment by tomkralidis** [comment]
Good idea!  Suggestions:

- let's get consensus on a standard header template
- I would do a flake8 sweep separate/after a consistent header sweep to have a single clean commit of the header sweep

**Comment by mgax** [comment]
I'd argue against spamming each source file with a copyright header. It's common practice to just provide a `LICENSE.txt` file at the top level of the repo. But I think making a single commit to clean up pep8 issues is a great idea.

**Comment by tomkralidis** [comment]
Having a standard header file is a requirement for OSGeo incubation and IMHO any project serious about copyright, distribution and related issues.

**Comment by mgax** [comment]
> any project serious about copyright

I submit to you a [source file](https://github.com/django/django/blob/master/django/db/models/__init__.py) from [the Django project](https://code.djangoproject.com), I believe they qualify as "serious" :) No copyright header in there. And maybe it's a good time to raise the issue about this particular OSGeo incubation requirement. :)

**Comment by tomkralidis** [comment]
@mgax thanks for the example ;)  Agree, worth a discussion, I will raise.

**Comment by tomkralidis** [comment]
Update: thread started in https://lists.osgeo.org/pipermail/incubator/2016-September/003165.html.

**Comment by ldesousa** [comment]
A Licence file does not replace a Copyright notice. In Europe Copyright applies by default, but this is not the case elsewhere (e.g. US). Therefore I would argue for a Copyright notice in each file header, with a reference to the Licence file.

**Comment by jorgejesus** [comment]
Hi to all 
Will had my 2 cents. Yes adding a big header is a pain and having to update the dates even worst, but is a job that has to be done, and better to be "pedantic" now than to be sorrow in the future, meaning I am more in favor of  a copyright notice in each file header, I think that the heard was the standard in the past but people and new project stopped using it.
 
I have read the comments on the thread started by Tom, and maybe a good solution would be a smaller header like this:

>/* (c) 2017 Open Source Geospatial Foundation - all rights reserved
 >* This code is licensed under the GPL 2.0 license, available at the root
 >* application directory.
 >*/ 
This is inline with the suggestion from @ldesousa

**Comment by ldesousa** [comment]
Precisely. The header needs only two lines: copyright notice and a reference to the licence file.

**Comment by tomkralidis** [comment]
Update: this turns out to be not a hard OSGeo requirement after some clarifications.  I'm okay with going with @ldesousa's suggestion.

**Comment by mgax** [comment]
How about this? I think the "all rights reserved" is implied if you state the copyright owner.
```python
# (c) 2017 OSGeo, licensed under GPL 2.0, see LICENSE.txt
```

**Comment by jorgejesus** [comment]
Shall we also include the development team ???? and the __author__ on the python code or not necessary?

`(c) 2017 OSGeo, licensed under GPL 2.0, see LICENSE.txt on root directory
PyWPS Development Team, represented by
PyWPS Project Steering Committe `

__author__ = "Santa's little helper"
__email__  = "santa@polenorte.com"

Any email is not a good idea to void spammer crawlers?

**Comment by ldesousa** [comment]
Most files have more than one author, I would leave that bit out. On the demo this might make sense, but I guess not here.

Another thing: I doubt we can have copyright assigned to mlre than one entity. I suggest something like: Copyright OSGeo Foundation, represented by the PyWPS PSC.

**Comment by jorgejesus** [comment]
**PyWPS3.2 authors and license for each file**
( done by command line and then checking each file)

|File|Author|License|
| --- | --- | --- |
|[pywps/etc/pywps.cfg-temp](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/etc/pywps.cfg-temp)|None|None|
|[pywps/Parser/DescribeProcess.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Parser/DescribeProcess.py)|Jachym Cepicky|GPL|
|[pywps/Parser/Execute.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Parser/Execute.py)|Jachym Cepicky|GPL|
|[pywps/Parser/Get.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Parser/Get.py)|Jachym Cepicky|GPL|
|[pywps/Parser/GetCapabilities.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Parser/GetCapabilities.py)|Jachym Cepicky|GPL|
|[pywps/Parser/Post.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Parser/Post.py)|Jachym Cepicky|GPL|
|[pywps/Parser/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Parser/__init__.py)|Jachym Cepicky|GPL|
|[pywps/processes/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/processes/__init__.py)|Jachym Cepicky|GPL|
|[pywps/processes/dummyprocess.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/processes/dummyprocess.py)|Jorge de Jesus|GPL|
|[pywps/processes/moreInOne.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/processes/moreInOne.py)|Jachym Cepicky|GPL|
|[pywps/processes/moreInstancesInOne.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/processes/moreInstancesInOne.py)|Jachym Cepicky|GPL|
|[pywps/processes/tests.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/processes/tests.py)|Jachym Cepicky|GPL|
|[pywps/processes/ultimatequestionprocess.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/processes/ultimatequestionprocess.py)|Jorge de Jesus|GPL|
|[pywps/Process/InAndOutputs.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Process/InAndOutputs.py)|Jachym Cepicky|GPL|
|[pywps/Process/Lang.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Process/Lang.py)|Jachym Cepicky|GPL|
|[pywps/Process/Process.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Process/Process.py)|Jachym Cepicky|GPL|
|[pywps/Process/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Process/__init__.py)|Jachym Cepicky|GPL|
|[pywps/Templates/1_0_0/inc/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/inc/__init__.py)|Jachym Cepicky|GPL|
|[pywps/Templates/1_0_0/inc/DescribeProcess_BoundingBoxValue.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/inc/DescribeProcess_BoundingBoxValue.tmpl)|None|None|
|[pywps/Templates/1_0_0/inc/DescribeProcess_ComplexValue.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/inc/DescribeProcess_ComplexValue.tmpl)|None|None|
|[pywps/Templates/1_0_0/inc/DescribeProcess_LiteralValue.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/inc/DescribeProcess_LiteralValue.tmpl)|None|None|
|[pywps/Templates/1_0_0/inc/Execute_Data_Inputs.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/inc/Execute_Data_Inputs.tmpl)|None|None|
|[pywps/Templates/1_0_0/inc/Execute_Data_Outputs.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/inc/Execute_Data_Outputs.tmpl)|None|None|
|[pywps/Templates/1_0_0/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/__init__.py)|Jachym Cepicky|GPL|
|[pywps/Templates/1_0_0/DescribeProcess.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/DescribeProcess.tmpl)|None|None|
|[pywps/Templates/1_0_0/Execute.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/Execute.tmpl)|None|None|
|[pywps/Templates/1_0_0/GetCapabilities.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/1_0_0/GetCapabilities.tmpl)|None|None|
|[pywps/Templates/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Templates/__init__.py)|Jachym Cepicky|GPL|
|[pywps/XSLT/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/XSLT/__init__.py)|Jachym Cepicky|GPL|
|[pywps/XSLT/describeProcess2WSDL.xsl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/XSLT/describeProcess2WSDL.xsl)|Jorge de Jesus|GPL|
|[pywps/XSLT/SOAP2WPS.xsl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/XSLT/SOAP2WPS.xsl)|Jorge de Jesus|GPL|
|[pywps/XSLT/WPS2SOAP.xsl](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/XSLT/WPS2SOAP.xsl)|Jorge de Jesus|GPL|
|[pywps/Wps/Execute/UMN.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Wps/Execute/UMN.py)|Jachym Cepicky|GPL|
|[pywps/Wps/Execute/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Wps/Execute/__init__.py)|Jachym Cepicky|GPL|
|[pywps/Wps/DescribeProcess.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Wps/DescribeProcess.py)|Jachym Cepicky|GPL|
|[pywps/Wps/GetCapabilities.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Wps/GetCapabilities.py)|Jachym Cepicky|GPL|
|[pywps/Wps/Wsdl.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Wps/Wsdl.py)|Jachym Cepicky & Jorge de Jesus|GPL|
|[pywps/Wps/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Wps/__init__.py)|Jachym Cepicky|GPL|
|[pywps/Exceptions.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Exceptions.py)|Jachym Cepicky|GPL|
|[pywps/Ftp.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Ftp.py)|Soeren Gebbert|GPL|
|[pywps/Grass.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Grass.py)|Jachym Cepicky|GPL|
|[pywps/Soap.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Soap.py)|Jachym Cepicky & Jorge de Jesus|GPL|
|[pywps/Template.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/Template.py)|Jachym Cepicky|GPL|
|[pywps/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/__init__.py)|Jachym Cepicky|GPL|
|[pywps/config.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/config.py)|Jachym Cepicky|GPL|
|[pywps/response.py](https://github.com/geopython/pywps/blob/pywps-3.2/pywps/response.py)|Jachym Cepicky|GPL|
|[tests/processes/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/__init__.py)|Jachym Cepicky|GPL|
|[tests/processes/buffer.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/buffer.py)|Jachym Cepicky|GPL|
|[tests/processes/dummyprocess.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/dummyprocess.py)|Jachym Cepicky|GPL|
|[tests/processes/moreInOne.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/moreInOne.py)|Jachym Cepicky|GPL|
|[tests/processes/moreInstancesInOne.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/moreInstancesInOne.py)|Jachym Cepicky|GPL|
|[tests/processes/returner.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/returner.py)|Jachym Cepicky|GPL|
|[tests/processes/tests.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/tests.py)|Jachym Cepicky|GPL|
|[tests/processes/ultimatequestionprocess.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/processes/ultimatequestionprocess.py)|Jorge de Jesus|GPL|
|[tests/Templates/1_0_0/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/__init__.py)|Jachym Cepicky|GPL|
|[tests/Templates/1_0_0/inc/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/inc/__init__.py)|Jachym Cepicky|GPL|
|[tests/Templates/1_0_0/inc/DescribeProcess_BoundingBoxValue.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/inc/DescribeProcess_BoundingBoxValue.tmpl)|None|None|
|[tests/Templates/1_0_0/inc/DescribeProcess_ComplexValue.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/inc/DescribeProcess_ComplexValue.tmpl)|None|None|
|[tests/Templates/1_0_0/inc/DescribeProcess_LiteralValue.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/inc/DescribeProcess_LiteralValue.tmpl)|None|None|
|[tests/Templates/1_0_0/inc/Execute_Data_Inputs.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/inc/Execute_Data_Inputs.tmpl)|None|None|
|[tests/Templates/1_0_0/inc/Execute_Data_Outputs.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/inc/Execute_Data_Outputs.tmpl)|None|None|
|[tests/Templates/__init__.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/__init__.py)|Jachym Cepicky|GPL|
|[tests/Templates/1_0_0/DescribeProcess.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/DescribeProcess.tmpl)|None|None|
|[tests/Templates/1_0_0/Execute.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/Execute.tmpl)|None|None|
|[tests/Templates/1_0_0/GetCapabilities.tmpl](https://github.com/geopython/pywps/blob/pywps-3.2/tests/Templates/1_0_0/GetCapabilities.tmpl)|None|None|
|[tests/benchmark.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/benchmark.py)|Jorge de Jesus|GPL|
|[tests/envvars_tests.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/envvars_tests.py)|Jachym Cepicky|GPL|
|[tests/exception.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/exception.py)|Jachym Cepicky|GPL|
|[tests/exceptions.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/exceptions.py)|Jachym Cepicky|GPL|
|[tests/parser.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/parser.py)|Jachym Cepicky|GPL|
|[tests/perform_requests.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/perform_requests.py)|Jachym Cepicky|GPL|
|[tests/process_inits.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/process_inits.py)|Jachym Cepicky|GPL|
|[tests/schema_validation.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/schema_validation.py)|Jachym Cepicky|GPL|
|[tests/soap_tests.py](https://github.com/geopython/pywps/blob/pywps-3.2/tests/soap_tests.py)|Jachym Cepicky|GPL|
|[tests/resquests/HTTP_GET.txt](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/HTTP_GET.txt)|None|None|
|[tests/resquests/wps_describeprocess_exception_SOAP11.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_describeprocess_exception_SOAP11.xml)|None|None|
|[tests/resquests/wps_describeprocess_exception_SOAP12.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_describeprocess_exception_SOAP12.xml)|None|None|
|[tests/resquests/wps_describeprocess_request.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_describeprocess_request.xml)|None|None|
|[tests/resquests/wps_describeprocess_request_SOAP11RPC.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_describeprocess_request_SOAP11RPC.xml)|None|None|
|[tests/resquests/wps_describeprocess_request_all.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_describeprocess_request_all.xml)|None|None|
|[tests/resquests/wps_describeprocess_request_all_SOAP.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_describeprocess_request_all_SOAP.xml)|None|None|
|[tests/resquests/wps_describeprocess_request_dummyprocess.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_describeprocess_request_dummyprocess.xml)|None|None|
|[tests/resquests/wps_execute_request-base64.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-base64.xml)|None|None|
|[tests/resquests/wps_execute_request-bbox.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-bbox.xml)|None|None|
|[tests/resquests/wps_execute_request-complexinput-as-reference.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-complexinput-as-reference.xml)|None|None|
|[tests/resquests/wps_execute_request-complexinput-direct-rawdata-output.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-complexinput-direct-rawdata-output.xml)|None|None|
|[tests/resquests/wps_execute_request-complexinput-direct.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-complexinput-direct.xml)|None|None|
|[tests/resquests/wps_execute_request-complexinput-one-output-as-reference.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-complexinput-one-output-as-reference.xml)|None|None|
|[tests/resquests/wps_execute_request-complexinput-output-as-reference.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-complexinput-output-as-reference.xml)|None|None|
|[tests/resquests/wps_execute_request-literalinput-responsedocument.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-literalinput-responsedocument.xml)|None|None|
|[tests/resquests/wps_execute_request-literalinput.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-literalinput.xml)|None|None|
|[tests/resquests/wps_execute_request-noinputs.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-noinputs.xml)|None|None|
|[tests/resquests/wps_execute_request-rawdataoutput.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-rawdataoutput.xml)|None|None|
|[tests/resquests/wps_execute_request-responsedocument.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request-responsedocument.xml)|None|None|
|[tests/resquests/wps_execute_request_compress_SOAP.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request_compress_SOAP.xml)|None|None|
|[tests/resquests/wps_execute_request_flags_compress_SOAP.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request_flags_compress_SOAP.xml)|None|None|
|[tests/resquests/wps_execute_request_lineage.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request_lineage.xml)|None|None|
|[tests/resquests/wps_execute_request_reference_lineage.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request_reference_lineage.xml)|None|None|
|[tests/resquests/wps_execute_request_ultimate_compress_SOAP.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request_ultimate_compress_SOAP.xml)|None|None|
|[tests/resquests/wps_execute_request_ultimatequestion_SOAP.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_execute_request_ultimatequestion_SOAP.xml)|None|None|
|[tests/resquests/wps_getcapabilities_request.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_getcapabilities_request.xml)|None|None|
|[tests/resquests/wps_getcapabilities_request_SOAP11.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_getcapabilities_request_SOAP11.xml)|None|None|
|[tests/resquests/wps_getcapabilities_request_SOAP11RPC.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_getcapabilities_request_SOAP11RPC.xml)|None|None|
|[tests/resquests/wps_getcapabilities_request_SOAP12.xml](https://github.com/geopython/pywps/blob/pywps-3.2/tests/resquests/wps_getcapabilities_request_SOAP12.xml)|None|None|
|[doc/source/conf.py](https://github.com/geopython/pywps/blob/pywps-3.2/doc/source/conf.py)|Jachym Cepicky|GPL|
|[webclient/WPS.js](https://github.com/geopython/pywps/blob/pywps-3.2/webclient/WPS.js)|Jachym Cepicky|GPL|
|[webservices/cgi/pywps.cgi](https://github.com/geopython/pywps/blob/pywps-3.2/webservices/cgi/pywps.cgi)|Jachym Cepicky|GPL|
|[webservices/wsgi/wsgiwps.py](https://github.com/geopython/pywps/blob/pywps-3.2/webservices/wsgi/wsgiwps.py)|Jachym Cepicky|GPL|
|[webservices/tomcat/PywpsServlet.py](https://github.com/geopython/pywps/blob/pywps-3.2/webservices/tomcat/PywpsServlet.py)|Jachym Cepicky|GPL|
|[webservices/tomcat/web.xml](https://github.com/geopython/pywps/blob/pywps-3.2/webservices/tomcat/web.xml)|Jachym Cepicky|GPL|
|[webservices/mod_python/wps.py](https://github.com/geopython/pywps/blob/pywps-3.2/webservices/mod_python/wps.py)|Jachym Cepicky|GPL|
|[setup.py](https://github.com/geopython/pywps/blob/pywps-3.2/setup.py)|Jachym Cepicky|GPL|
|[wps.py](https://github.com/geopython/pywps/blob/pywps-3.2/wps.py)|Jachym Cepicky|GPL|

**Comment by jachym** [comment]
Hi,

short (2 lines) copyright header is fine

Forget about Jachym Cepicky - it's PyWPS PSC. 

Authors can change - leave them out, git will tell

just my 0.02

**Comment by jorgejesus** [comment]
**PyWPS4-master authors and license for each file**
( done by command line and then checking each file)

|File|Author|License|
| --- | --- | --- |
|[docs/Makefile](https://github.com/geopython/pywps/blob/master/docs/Makefile)|None|None|
|[docs/conf.py](https://github.com/geopython/pywps/blob/master/docs/conf.py)|PSC|MIT|
|[docs/demobuffer.py](https://github.com/geopython/pywps/blob/master/docs/demobuffer.py)|Jachym Cepicky|MIT|
|[tests/test_inout.py](https://github.com/geopython/pywps/blob/master/tests/test_inout.py)|PSC|MIT|
|[tests/process.py](https://github.com/geopython/pywps/blob/master/tests/process.py)|PSC|MIT|
|[tests/processes/__init__.py](https://github.com/geopython/pywps/blob/master/tests/processes/__init__.py)|PSC|MIT|
|[tests/data/point.xsd](https://github.com/geopython/pywps/blob/master/tests/data/point.xsd)|None|None|
|[tests/validator/__init__.py](https://github.com/geopython/pywps/blob/master/tests/validator/__init__.py)|PSC|MIT|
|[tests/validator/test_literalvalidators.py](https://github.com/geopython/pywps/blob/master/tests/validator/test_literalvalidators.py)|PSC|MIT|
|[tests/validator/test_complexvalidators.py](https://github.com/geopython/pywps/blob/master/tests/validator/test_complexvalidators.py)|PSC|MIT|
|[tests/test_execute.py](https://github.com/geopython/pywps/blob/master/tests/test_execute.py)|PSC|MIT|
|[tests/__init__.py](https://github.com/geopython/pywps/blob/master/tests/__init__.py)|PSC|MIT|
|[tests/requests/wps_execute_request_extended-responsedocument.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_execute_request_extended-responsedocument.xml)|None|None|
|[tests/requests/wps_describeprocess_request.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_describeprocess_request.xml)|None|None|
|[tests/requests/wps_getcapabilities_request.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_getcapabilities_request.xml)|None|None|
|[tests/requests/wps_execute_request_rawdataoutput.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_execute_request_rawdataoutput.xml)|None|None|
|[tests/requests/wps_execute_request-complexvalue.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_execute_request-complexvalue.xml)|None|None|
|[tests/requests/wps_execute_request-responsedocument-2.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_execute_request-responsedocument-2.xml)|None|None|
|[tests/requests/__init__.py](https://github.com/geopython/pywps/blob/master/tests/requests/__init__.py)|PSC|MIT|
|[tests/requests/wps_execute_request-boundingbox.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_execute_request-boundingbox.xml)|None|None|
|[tests/requests/wps_execute_request-responsedocument-1.xml](https://github.com/geopython/pywps/blob/master/tests/requests/wps_execute_request-responsedocument-1.xml)|None|None|
|[tests/test_wpsrequest.py](https://github.com/geopython/pywps/blob/master/tests/test_wpsrequest.py)|PSC|MIT|
|[tests/test_exceptions.py](https://github.com/geopython/pywps/blob/master/tests/test_exceptions.py)|PSC|MIT|
|[tests/common.py](https://github.com/geopython/pywps/blob/master/tests/common.py)|PSC|MIT|
|[tests/test_literaltypes.py](https://github.com/geopython/pywps/blob/master/tests/test_literaltypes.py)|PSC|MIT|
|[tests/test_describe.py](https://github.com/geopython/pywps/blob/master/tests/test_describe.py)|PSC|MIT|
|[tests/test_ows.py](https://github.com/geopython/pywps/blob/master/tests/test_ows.py)|PSC|MIT|
|[tests/test_formats.py](https://github.com/geopython/pywps/blob/master/tests/test_formats.py)|PSC|MIT|
|[tests/test_assync.py](https://github.com/geopython/pywps/blob/master/tests/test_assync.py)|PSC|MIT|
|[tests/test_capabilities.py](https://github.com/geopython/pywps/blob/master/tests/test_capabilities.py)|PSC|MIT|
|[tests/test_dblog.py](https://github.com/geopython/pywps/blob/master/tests/test_dblog.py)|PSC|MIT|
|[pywps/inout/formats/__init__.py](https://github.com/geopython/pywps/blob/master/pywps/inout/formats/__init__.py)|PSC|MIT|
|[pywps/inout/inputs.py](https://github.com/geopython/pywps/blob/master/pywps/inout/inputs.py)|PSC|MIT|
|[pywps/inout/storage.py](https://github.com/geopython/pywps/blob/master/pywps/inout/storage.py)|PSC|MIT|
|[pywps/inout/__init__.py](https://github.com/geopython/pywps/blob/master/pywps/inout/__init__.py)|PSC|MIT|
|[pywps/inout/outputs.py](https://github.com/geopython/pywps/blob/master/pywps/inout/outputs.py)|PSC|MIT|
|[pywps/inout/basic.py](https://github.com/geopython/pywps/blob/master/pywps/inout/basic.py)|PSC|MIT|
|[pywps/inout/literaltypes.py](https://github.com/geopython/pywps/blob/master/pywps/inout/literaltypes.py)|PSC|MIT|
|[pywps/validator/allowed_value.py](https://github.com/geopython/pywps/blob/master/pywps/validator/allowed_value.py)|PSC|MIT|
|[pywps/validator/base.py](https://github.com/geopython/pywps/blob/master/pywps/validator/base.py)|PSC|MIT|
|[pywps/validator/literalvalidator.py](https://github.com/geopython/pywps/blob/master/pywps/validator/literalvalidator.py)|PSC|MIT|
|[pywps/validator/complexvalidator.py](https://github.com/geopython/pywps/blob/master/pywps/validator/complexvalidator.py)|PSC|MIT|
|[pywps/validator/__init__.py](https://github.com/geopython/pywps/blob/master/pywps/validator/__init__.py)|PSC|MIT|
|[pywps/validator/mode.py](https://github.com/geopython/pywps/blob/master/pywps/validator/mode.py)|PSC|MIT|
|[pywps/app/WPSRequest.py](https://github.com/geopython/pywps/blob/master/pywps/app/WPSRequest.py)|PSC|MIT|
|[pywps/app/basic.py](https://github.com/geopython/pywps/blob/master/pywps/app/basic.py)|PSC|MIT|
|[pywps/app/__init__.py](https://github.com/geopython/pywps/blob/master/pywps/app/__init__.py)|PSC|MIT|
|[pywps/app/Process.py](https://github.com/geopython/pywps/blob/master/pywps/app/Process.py)|PSC|MIT|
|[pywps/app/Service.py](https://github.com/geopython/pywps/blob/master/pywps/app/Service.py)|PSC|MIT|
|[pywps/app/WPSResponse.py](https://github.com/geopython/pywps/blob/master/pywps/app/WPSResponse.py)|PSC|MIT|
|[pywps/dependencies.py](https://github.com/geopython/pywps/blob/master/pywps/dependencies.py)|PSC|MIT|
|[pywps/wpsserver.py](https://github.com/geopython/pywps/blob/master/pywps/wpsserver.py)|PSC|MIT|
|[pywps/resources/schemas/__init__.py](https://github.com/geopython/pywps/blob/master/pywps/resources/schemas/__init__.py)|PSC|MIT|
|[pywps/resources/schemas/wps_all.xsd](https://github.com/geopython/pywps/blob/master/pywps/resources/schemas/wps_all.xsd)|None|None|
|[pywps/resources/__init__.py](https://github.com/geopython/pywps/blob/master/pywps/resources/__init__.py)|PSC|MIT|
|[pywps/exceptions.py](https://github.com/geopython/pywps/blob/master/pywps/exceptions.py)|PSC|MIT|
|[pywps/_compat.py](https://github.com/geopython/pywps/blob/master/pywps/_compat.py)|Alex Morega|MIT|
|[pywps/__init__.py](https://github.com/geopython/pywps/blob/master/pywps/__init__.py)|PSC|MIT|
|[pywps/configuration.py](https://github.com/geopython/pywps/blob/master/pywps/configuration.py)|Calin Ciociu|MIT|
|[pywps/dblog.py](https://github.com/geopython/pywps/blob/master/pywps/dblog.py)|PSC|MIT|
|[setup.py](https://github.com/geopython/pywps/blob/master/setup.py)|PSC|MIT|

**Comment by jorgejesus** [comment]
From the  multiple comments, I think we more or less agree on:
PyWPS3-2:
`
Copyright 2016 OSGeo Foundation, represented PyWPS Project Steering Committe, licensed under GPL 2.0, see LICENSE.txt on root directory. 
`
PyWPS4.0(master)
`
Copyright 2016 OSGeo Foundation, represented PyWPS Project Steering Committe, licensed under MIT, see LICENSE.txt on root directory. 
`
Personal authors only relevant on demos. 
Do we need a final approval vode?

**Comment by tomkralidis** [comment]
I would remove '`on root directory`', otherwise looks good to me.

+1 to put to a vote.

**Comment by jorgejesus** [comment]
+1 (also vote for remove of on root directory)

**Comment by ldesousa** [comment]
+1 
I usually wirte something like: "Please consult the LICENCE file for details."

**Comment by jorgejesus** [comment]
Implementing
PyWPS3-2:
`
Copyright 2016 OSGeo Foundation, represented PyWPS Project Steering Committe, licensed under GPL 2.0, Please consult LICENSE.txt for details. 
`
PyWPS4.0(master)
`
Copyright 2016 OSGeo Foundation, represented PyWPS Project Steering Committe, licensed under MIT, Please consult LICENSE.txt for details.

**Comment by jorgejesus** [comment]
Everything done made two pull requests #192 #193, when they are accepted please close issue

**Comment by tomkralidis** [comment]
Thanks all!
