### ISSUE TITLE
Writing unit tests for wps processes

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#197]
I want to write some unit tests for my own processes. PyWPS has already something in `tests/common.py` which i can probably use but this module is not in the `pywps` namespace.

Is it planned to provide some base classes for unit testing?

**Comment by jachym** [comment]
Hi,

you should be able to "from tests import common"

what is your usecase? do you want to write unittests based on pywps deployment?

wouldn't it be more useful to write "integreation tests" - something using OWSLib, which would communicate directly with your PyWPS deployment, rather then using direct Python classes?

Just asking

**Comment by cehbrecht** [comment]
the `tests` module is not packaged with pywps. If you provide common tests classes they probably should have the `pywps` namespace.

I want to have two types of tests. Using the pywps test modules i can run quick process tests without starting a service. In addition i also have "integration tests" with started services and using owslib.

**Comment by ldesousa** [comment]
The idea is for these tests to be coded in the application itself (e.g pywps-demo). If you wish to test your processes without starting the service, then you should not need the PyWPS namespace. Unless I am missing something...

**Comment by cehbrecht** [comment]
i would like to use `tests.common.py` (at least parts of it like `client_for`) to write tests for my own processes (pywps is included as python dependency).

**Comment by jachym** [comment]
@chbrecht - it makes sense to me, that you download the whole source code and point your tests to it

```
import sys
sys.path.append('/src/local/pywps-4/')
from tests import common
```

Or maybe something more sophisticated, using importlib described here http://stackoverflow.com/questions/67631/how-to-import-a-module-given-the-full-path would help?

We could bring this to PSC meeting

**Comment by cehbrecht** [comment]
@jachym 
for now i have copied what i need from `test.common.py`, so i can of course live with that. But would be nice to have a common wps test setup.

**Comment by jachym** [comment]
@cehbrecht would this commit make your life easier ? https://github.com/jachym/PyWPS/commit/c7f60c6ec5e500ee26d71af74343eff494f820a7 shall I pull?

**Comment by jachym** [comment]
@cehbrecht ping? do you need this in pywps 4.0.0 release?
