### ISSUE TITLE
Compile a list of scientific papers, projects being used by pyWPS 

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pywps#206]
# Description

Compile a list of scientific papers, projects being used by pyWPS 

# Environment

PyWPS website

- operating system:
- Python version:
- PyWPS version:
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [x] other (please specify):
pywps website 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by jorgejesus** [comment]
List send by @ggiuliani

Following your call for a list of Scientific articles where PyWPS has been used (http://pywps.org/science/), here is some addition:
- Lacroix P./Guigoz Y., Rouholahnejad E., Ray N., Giuliani G. (2016) SCOPED-W: Scalable Online Platform for extracting Environmental Data and Water-related model outputs. Transactions in GIS
[http://onlinelibrary.wiley.com/doi/10.1111/tgis.12227/full](http://onlinelibrary.wiley.com/doi/10.1111/tgis.12227/full)
- Giuliani G., Lacroix P., Guigoz Y., Roncella R., Bigagli L., Santoro M., Mazzetti P., Nativi S., Ray N., Lehmann A. (2016) Bringing GEOSS services into practice: a capacity building resource on spatial data infrastructures (SDI). Transactions in GIS
http://onlinelibrary.wiley.com/doi/10.1111/tgis.12209/full
- Giuliani G., Rahman K., Ray N., Lehmann A. (2013) OWS4SWAT: Publishing and Sharing SWAT Outputs with OGC standards. International Journal of Advanced Computer Science and Applications EnviroGRIDS Special Issue on "Building a Regional Observation System in the Black Sea Catchment":90-98
http://thesai.org/Publications/ViewPaper?Volume=3&Issue=3&Code=SpecialIssue&SerialNo=11
- Giuliani G., Nativi S., Lehmann A., Ray N. (2012) WPS mediation: an approach to process geospatial data on different computing backends. Computers and Geosciences 47:20-33
http://www.sciencedirect.com/science/article/pii/S0098300411003402

hope this can help.

Regards

**Comment by jorgejesus** [comment]
Science direct + WUR library + Google scholar
- Erlich,Marc, Christophe Coulet, and Arnaud De Groof. "Towards improved management of coastal submersion crises–CRISMA-WAVE solution as an example of CRISMA Framework application." E3S Web of Conferences. Vol. 3. EDP Sciences, 2016.

- Kadygrov, Nikolay, et al. "Implementation of Web Processing Services (WPS) over IPSL Earth System Grid Federation (ESGF) node." EGU General Assembly Conference Abstracts. Vol. 18. 2016.

- Eberle, Jonas, et al. "Multi-Source Data Integration and Analysis for Land Monitoring in Siberia." Novel Methods for Monitoring and Managing Land and Water Resources in Siberia. Springer International Publishing, 2016. 471-487.

- Marchesini, Ivan, et al. "A Spatial Data Infrastructure for Landslides and Floods in Italy." EGU General Assembly Conference Abstracts. Vol. 12. 2010.

- Lindquist, E. J., et al. "Improving Access, Utility and Analyses of FAO Forestry Statistics via Geographic Web-based Services." IEEE Earthzine 5.2 (2012): 378146.

- de Jesus, Jorge, et al. "WPS orchestration using the Taverna workbench: The eScience approach." Computers & Geosciences 47 (2012): 75-86.

- Kumar, Kavisha, and Sameer Saran. "Web based geoprocessing tool for coverage data handling." The International Archives of Photogrammetry, Remote Sensing and Spatial Information Sciences 40.8 (2014): 1139.

- Goodall, J. L., et al. "Application of the Open Geospatial Consortium (OGC) Web Processing Service (WPS) Standard for Exposing Water Models as Web Services." AGU Fall Meeting Abstracts. Vol. 1. 2012.

- Vitolo, Claudia, et al. "Cloud-enabled Web Applications for Environmental Modelling." AGU Fall Meeting Abstracts. Vol. 1. 2012.

- Dubois, Grégoire, et al. "eHabitat, a multi-purpose Web Processing Service for ecological modeling." Environmental Modelling & Software 41 (2013): 123-133.

**Comment by geoslegend** [comment]
I presented my research using PyWPS. Here, there is the information:

- Lee, Seongkyu (2016, August). Development of OGC WPS-based Climate Data Visualization Service Using PyWPS and Matplotlib. In Proceedings of Free and Open Source Software for Geospatial (FOSS4G) BONN 2016, WCCB, BONN, Germany.

**Comment by tomkralidis** [comment]
Used by WMO [WOUDC](http://woudc.org) in support of data validation services:

http://www.opengeospatial.org/blog/2418

**Comment by jachym** [comment]
@geoslegend yes, I still have the PDF and was not sure, where to place it - @jorgejesus , can I pass you the PDF via mail?

**Comment by jachym** [comment]
Just removing 4.0.0 milestone label - this is not related to release IMHO

**Comment by ldesousa** [comment]
iGUESS is the project I worked on while at LIST: http://iguess.list.lu/

Just for reference, the publication list I gathered some months ago: http://pywps.org/science/

**Comment by jorgejesus** [comment]
@ldesousa I have used your list and updated with more content. See  it on my fork
[https://github.com/jorgejesus/pywps.org/blob/gh-pages/science/index.md](https://github.com/jorgejesus/pywps.org/blob/gh-pages/science/index.md)

**Comment by ldesousa** [comment]
We should find something for 2011...

**Comment by jorgejesus** [comment]
I have been looking for 2011 but nothing specific to PyWPS some generic papers about WPS

**Comment by jorgejesus** [comment]
@ldesousa @jachym @tomkralidis  Shall we have an indepent section about projects (like science). Or just as a section at the bottom or more top of science?

**Comment by ldesousa** [comment]
@jorgejesus I would vote for an independent section on projects.

**Comment by tomkralidis** [comment]
+1 agree with @ldesousa 
Is there a publication hub we can simply/additionally link to (like researchgate, google scholar, etc.)?

**Comment by jorgejesus** [comment]
@jachym The  HUMBOLDT Harmonisation Toolkit / project did they used pywps ?? I have the idea of some work done concerning Jython and PyWPS?

**Comment by jorgejesus** [comment]
Project list
https://github.com/jorgejesus/pywps.org/blob/gh-pages/projects/index.md
If OK will make a pull request

**Comment by jachym** [comment]
It used to use PyWPS for WPS interace using Jython, but it's gone long time ago

On the other hand - they used it, so it's legit to reference it http://www.esdi-humboldt.eu/home.html 

I've found this https://books.google.cz/books?id=9Ap61P2NiTIC&pg=PA147&lpg=PA147&dq=humboldt+project+pywps&source=bl&ots=dou7S7JFWU&sig=DRpO5qlisir9DQCGf6ea9otLf_4&hl=cs&sa=X&ved=0ahUKEwi-o6PezbXQAhUCsxQKHSV8A8wQ6AEIPDAE#v=onepage&q=humboldt%20project%20pywps&f=false

and 

http://apps.esdi-humboldt.cz/cgi-bin/pywps_3_0?service=wps&request=getcapabilities

**Comment by geoslegend** [comment]
I have released OpenWPS (Web Processing Service) service related to 

> Lee, Seongkyu (2016, August). Development of OGC WPS-based Climate Data Visualization Service Using PyWPS and Matplotlib. In Proceedings of Free and Open Source Software for Geospatial (FOSS4G) BONN 2016, WCCB, BONN, Germany.

Also, I have developed and released a masking service with new algorithm using PyWPS 4.0 in this year (2016). Maybe the masking service will be presented in FOSS4G 2017 BOSTON.

If you want to use the service, please visit OpenWPS website (http://openwps.apcc21.org/). Please do not hesitate to contact me if you have any questions.

Happy new year !

**Comment by jachym** [comment]
Hi  Seongkyu,

good work! Looking forward to more processes and your experience with 
PyWPS 4

Thank you for sharing

J

Dne 29.12.2016 v 18:48 Seongkyu Lee napsal(a):
> I have released OpenWPS (Web Processing Service) service related to
>
>> Lee, Seongkyu (2016, August). Development of OGC WPS-based Climate Data Visualization Service Using PyWPS and Matplotlib. In Proceedings of Free and Open Source Software for Geospatial (FOSS4G) BONN 2016, WCCB, BONN, Germany.
>
> Also, I have developed and released a masking service with new algorithm using PyWPS 4.0 in this year (2016). Maybe the masking service will be presented in FOSS4G 2017 BOSTON.
>
> If you want to use the service, please visit OpenWPS website (http://openwps.apcc21.org/). Please do not hesitate to contact me if you have any questions.
>
> Happy new year !
>

-- 
Jachym Cepicky
e-mail: jachym.cepicky@gmail.com
twitter: @jachymc
