### ISSUE TITLE
Service error: Broken pipe

### ISSUE THREAD

**Issue by geoslegend** [geopython/pywps#211]
# Description

Hi, all. I have tried to develop wps services on windows 8 64bit. 

The errors in both server and client sides were shown as

- server side
```
2016-11-07 14:52:32,924 INFO sqlalchemy.engine.base.Engine ()
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "D:\dev\python27_64\lib\multiprocessing\forking.py", line 380, in main
    prepare(preparation_data)
  File "D:\dev\python27_64\lib\multiprocessing\forking.py", line 489, in prepare

    file, path_name, etc = imp.find_module(main_name, dirs)
ImportError: No module named demo
```

- client side
```
<!-- PyWPS 4.0.0rc2 -->
<ows:ExceptionReport xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/ows/1.1 http://schemas.opengis.net/ows/1.1.0/owsExceptionReport.xsd" version="1.0.0">
  <ows:Exception exceptionCode="NoApplicableCode" locator="" >
      <ows:ExceptionText>Service error: [Errno 32] Broken pipe</ows:ExceptionText>
  </ows:Exception>
</ows:ExceptionReport>
```

I already tested the wps service after installing demo. How to solve this problem?

# Environment

- operating system: Windows 8 64bit
- Python version: 2.7.10 64bit
- PyWPS version: 4.0.0rc2 (cloned on Nov. 07, 2016)
- source/distribution
 - [ O ] git clone (Nov. 07, 2016)
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ O ] other (please specify): demo.py

# Steps to Reproduce

# Additional Information

**Comment by jachym** [comment]
Could you possibly pass your configuration file? How do you start the PyWPS-demo deployment? Using python3 demo.py command? What is do documentation you were taking and it does not work?

Thanks

**Comment by geoslegend** [comment]
@jachym I just used the command 'python2 demo.py' with the default configuration file. I can run the pywps service on Windows OS as you know but the above errors are shown when calling the wps service.

The sample code is
```
execution = wps.execute(processid, inputs, output = 'OUTPUT')
print execution.checkStatus()
```

Thanks //

**Comment by jachym** [comment]
Still not sure, where this could occure. I do note see any "demo" string used in our code base  (both PyWPS and pywps-demo). Just in the `setup.py` script of pywps-demo.

Are you saying, that you are running

```
cd pywps-demo
python2 demo.py
```

without problem, and then, when calling

http://localhost:5000/wps?service=wps&request=getcapabilities

You get this error?

Thanks for help

P.S. Sorry for late resposne, the notification slipped through my mailbox.

**Comment by ldesousa** [comment]
PyWPS does not support Windows, the Multiprocessing library does not work on that system. Closing this issue as no obvious cause has been found.
