### ISSUE TITLE
Release announcement and upgrade notes

### ISSUE THREAD

**Issue by cskarby** [geopython/pywps#216]
Congratulations on the 4.0 release!

I am wondering if you could share some news about what's new in v4.0 and what's changed since v3, please. I guess the [github release page](https://github.com/geopython/pywps/releases) (or the main readme) would be places where I will be looking for this kind of information. I was happy to find the [docs/migration.rst](https://github.com/geopython/pywps/blob/master/docs/migration.rst) file, but it seems to be just a placeholder for now.

Keep up the good work! I am looking forward to hear what an upgrade to v4 will bring to the table, and how we should proceed from v3 to v4 :)

Best regards,
Christian

**Comment by jachym** [comment]
Hi,

sorry, you made very good point. I'm going to work on the migrations.rst 
during Christmas holidays

Thanks for pointing this out

Jachym

Dne 9.12.2016 v 16:21 Christian Skarby napsal(a):
> Congratulations on the 4.0 release!
>
> I am wondering if you could share some news about what's new in v4.0 and what's changed since v3, please. I guess the [github release page](https://github.com/geopython/pywps/releases) (or the main readme) would be places where I will be looking for this kind of information. I was happy to find the [docs/migration.rst](https://github.com/geopython/pywps/blob/master/docs/migration.rst) file, but it seems to be just a placeholder for now.
>
> Keep up the good work! I am looking forward to hear what an upgrade to v4 will bring to the table, and how we should proceed from v3 to v4 :)
>
> Best regards,
> Christian
>

-- 
Jachym Cepicky
e-mail: jachym.cepicky@gmail.com
twitter: @jachymc

**Comment by jachym** [comment]
Hi @cskarby 

would this be ok for you? https://github.com/geopython/pywps/pull/224 

Not sure, if it's useful text for someone, who needs to migrate - thanks for any feedback.

**Comment by cskarby** [comment]
Hi @jachym this is very valuable at least for me with a technical background. I have had a quick read and this is a lot more than nothing! Unfortunately I am not directly involved in any related projects at the moment, so I will not have time to test and give extensive feedback, but this gives me a ballpoint figure about what a conversion would require. Thanks a lot!

**Comment by jachym** [comment]
Thanks for feedback

Dne 6.1.2017 v 13:41 Christian Skarby napsal(a):
> Hi @jachym this is very valuable at least for me with a technical background. I have had a quick read and this is a lot more than nothing! Unfortunately I am not directly involved in any related projects at the moment, so I will not have time to test and give extensive feedback, but this gives me a ballpoint figure about what a conversion would require. Thanks a lot!
>

-- 
Jachym Cepicky
e-mail: jachym.cepicky@gmail.com
twitter: @jachymc
