### ISSUE TITLE
Exception: Maximum number of parallel running processes reached in apache httpd daemon

### ISSUE THREAD

**Issue by geoslegend** [geopython/pywps#217]
# Description

I develop a wps service based on pywps 4.0.0 with gdal, shapely, etc and I test on apache httpd daemon instead of demo.py. There weren't  any errors in previous version (before 4.0.0 release), but after upgrading to pywps 4.0.0, the error message was shown as
> 2016-12-12 11:35:14,266] [ERROR] file=/xxx/2.7.10/lib/python2.7/site-packages/pywps-4.0.0-py2.7.egg/pywps/exceptions.py line=45 module=exceptions function=__init__ Exception: code: 400, locator: Maximum number of parallel running processes reached. Please try later., description: 
> None

I guess that such error caused by maxprocesses and parallelprocesses options in [Server] section in 'pywps.cfg' file. I don't change them. They are as
```
maxprocesses=10
parallelprocesses=2
```

# Environment

- operating system: CentOS 6.5 (Final)
- Python version: 2.7.10 (GCC 4.4.7) 64bit
- PyWPS version: 4.0.0
- source/distribution
 - [O] git clone (cloned Dec. 09, 2016)
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [O] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
i) Upgrade to new version (PyWPS 4.0.0)
ii) Restart apache httpd daemon
iii) Call a wps operator

# Additional Information
There isn't the name, prefix, in 'logging' section in a config file. When upgrading to new version (4.0.0), I missed the check of the configuration file. By the way, I wonder why a pywps process on the apache httpd daemon is automatically repeated.

**Comment by jachym** [comment]
Hi (sorry for late response),

the question is, whether, it's bug in PyWPS or whether really maximum number of accepted processes was reached.

`maxprocesses=10` - means, there can be at maximum 10 requests waiting in the que

`parallelprocesses=2` - means, only two process instances can run at time

is there chance, there is more then 10 requests comming in a time?

Could you have a look into your database, how many records are in `pywps_stored_requests` table? How do the statuses look in `pywps_requests` table?

Sorry for caused troubles.

**Comment by aoyono** [comment]
Had the same issue, deleted all the content of `pywps_requests` table and everything went back to normal

**Comment by ldesousa** [comment]
This is a problem with SQlite itself, that is [not updating the database content in time](https://www.sqlite.org/whentouse.html):

> SQLite supports an unlimited number of simultaneous readers, but it will only allow one writer at any instant in time.

This is not the case with a real database system like Postgres. In a production environment SQLite is not at all advisable.
