### ISSUE TITLE
Update developer's guide

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps#221]
The developer's guide must be updated with information on the develop branch:
. pull requests
. item branches
. other upstream repositories (?)

To close this task the develop branch must become the main project branch. This is subject to approval by the PSC.

The PyWPS development method is inspired on this branching model:
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by jachym** [comment]
Works for me. Let's start the proposed approach.

One note: do we than need to distinguish between odd and even numbers in our versions? With proposed approach, we can nicely continue with 4.1 as next stable release number (?)

+ 1 for me as PSC member

**Comment by ldesousa** [comment]
The develop branch must be referred in the following files:

https://github.com/geopython/pywps/blob/master/CONTRIBUTING.rst
https://github.com/geopython/pywps/blob/master/RELEASE-howto.md
https://github.com/geopython/pywps/blob/master/docs/development.rst

**Comment by tomkralidis** [comment]
@jachym I'd prefer even/odd strategy as this clearly indicates a stable/unstable version.
