### ISSUE TITLE
Can pywps be installed with pip?

### ISSUE THREAD

**Issue by Alexander-Barth** [geopython/pywps#227]
# Description

I am wondering if pywps is supposed to be installable using pip. Currently pip only finds an old version not installable using python 3.4

# Environment

- operating system:
Ubuntu 14.04
- Python version:
Python 3.4.3
- PyWPS version:
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
pip
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
```bash
$ pip3 install --user pywps==4.0.0
Downloading/unpacking pywps==4.0.0
  Could not find a version that satisfies the requirement pywps==4.0.0 (from versions: 3.2.6)
Cleaning up...
No distributions matching the version for pywps==4.0.0
Storing debug log for failure in /home/abarth/.pip/pip.log
```
without requiring any version:

```
 pip3 install --user pywps
Downloading/unpacking pywps
  Downloading pywps-3.2.6.tar.gz (123kB): 123kB downloaded
  Running setup.py (path:/tmp/pip_build_abarth/pywps/setup.py) egg_info for package pywps
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip_build_abarth/pywps/setup.py", line 32
        print "Compiling template "+template_file+" in "+base
                                  ^
    SyntaxError: Missing parentheses in call to 'print'
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 17, in <module>

  File "/tmp/pip_build_abarth/pywps/setup.py", line 32

    print "Compiling template "+template_file+" in "+base

                              ^

SyntaxError: Missing parentheses in call to 'print'

----------------------------------------
Cleaning up...
Command python setup.py egg_info failed with error code 1 in /tmp/pip_build_abarth/pywps
Storing debug log for failure in /home/abarth/.pip/pip.log
```

# Additional Information

**Comment by ldesousa** [comment]
I am getting similar errors, even though the [PyPi repository](https://pypi.org/project/pywps/#history) reports 4.0.0 as the latest version.

**Comment by Alexander-Barth** [comment]
Thank you, for checking.

Am 18.01.2017 8:23 nachm. schrieb "Luís de Sousa" <notifications@github.com

**Comment by jachym** [comment]
No idea :-( http://stackoverflow.com/questions/41757965/pip-installs-old-version-of-package

**Comment by SiggyF** [comment]
I answered your question at https://stackoverflow.com/a/44249121/386327.  The current pypi list contains only .egg files for new releases. These are not supported by pip. So it finds the old .tar.gz file, which is supported. I suggest to also upload .whl files. Please let me know if you need some help with this.

**Comment by jachym** [comment]
ok guys, that was the trick - use bdist_wheel

sorry it took so long, pywps-4.0.0 should be installable via `pip install` now (can you prove?)

**Comment by SiggyF** [comment]
Tested with an empty 3.5 virtual env. It works fine now, `pywps-4.0.0-py3-none-any.whl` got installed.
