### ISSUE TITLE
Hook up RTD to the develop branch

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps#231]
The RTD project must be updated to use the `develop` by default. 

Log on to RTD and select the `pywps` project. Then go to *Admin* > *Advanced Settings* and at mid page insert `develop` in the *Default branch:* box. Then click *Submit* at the bottom of the page.

Alternatively, you can make me owner of the `pywps` project ;)

**Comment by tomkralidis** [comment]
Update: we are currently discussing `develop` and `master` branch development and should have a way forward in a day or two to be able to address this issue.

**Comment by ldesousa** [comment]
[PSC vote](https://lists.osgeo.org/pipermail/pywps-dev/2018-March/001216.html) on merging `develop` with `master`.

**Comment by tomkralidis** [comment]
Closing given `develop` branch is now defunct/gone.
