### ISSUE TITLE
pywps 4.x on conda-forge

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#234]
# Description

i've added pywps 4.x to conda-forge:
https://github.com/conda-forge/pywps-feedstock

The conda package is currently build from github source using tag 4.0.0.

Would be nice if the conda package has more maintainers :)

**Comment by ldesousa** [comment]
This might need an update to the release how-to:
https://github.com/geopython/pywps/blob/develop/RELEASE-howto.md

**Comment by cehbrecht** [comment]
I will take care about it after 4.2.0 release.

**Comment by cehbrecht** [comment]
The 4.2.1 release works. The conda-forge package was automatically updated from pypi.
https://anaconda.org/conda-forge/pywps
