### ISSUE TITLE
Pywps4 intermittently can't find the workdir when handling several requests

### ISSUE THREAD

**Issue by kvold** [geopython/pywps#235]
# Description
When PyWps is hit by several requests a second it is not able to handle all of them, and crashes on a subset of the requests.

It seems like sqlalchemy runs into a series of problem, and at some point PyWps4 is no longer able to access the working directory.
The crash might be caused by a race-condition when creating/deleting/accessing the workdir. Probably related to #228 , but the error-message is somewhat different (see the attached errorlog for the full message):
[Wed Feb 15 10:08:16.197536 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633] mod_wsgi (pid=23536): Exception occurred processing WSGI script '/usr/local/pywps/pywps.wsgi'.
[Wed Feb 15 10:08:16.197618 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633] Traceback (most recent call last):
[Wed Feb 15 10:08:16.198342 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633]   File "/usr/lib64/python3.4/site-packages/werkzeug/wrappers.py", line 291, in application
[Wed Feb 15 10:08:16.198356 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633]     return f(*args[:-2] + (request,))(*args[-2:])
[Wed Feb 15 10:08:16.198661 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633]   File "/usr/local/wps/src/pywps/pywps/app/Service.py", line 583, in __call__
[Wed Feb 15 10:08:16.198672 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633]     request_uuid
[Wed Feb 15 10:08:16.198712 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633]   File "/usr/local/wps/src/pywps/pywps/app/Service.py", line 308, in execute
[Wed Feb 15 10:08:16.198720 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633]     os.chdir(olddir)
[Wed Feb 15 10:08:16.198751 2017] [wsgi:error] [pid 23536] [remote *.*.*.*:3633] FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/pywps/workdir/pywps_process_slaw0mff'

# Environment

- operating system: Centos 7
- Python version: 3.4.5
- PyWPS version: 4.0.0
- source/distribution
 - [X] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify):
- web server
 - [X] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify):

# Steps to Reproduce
"Stress" a process simply by quickly hitting f5 when performing a request through the browser. The process I tested it on is somewhat demanding and takes about 40-80ms to finish.

# Additional Information
See the attached Apache errorlog.
[multipleRequests.txt](https://github.com/geopython/pywps/files/776650/multipleRequests.txt)

**Comment by sylvainbeo** [comment]
Hi,
I've got the same behaviour. 
@kvold did you find a solution ?

**Comment by sylvainbeo** [comment]
I thunk i've temporary solved the problem by passing the os.chdir command :

Service.py (execute)

`        try:
            os.chdir(process.workdir)
            response = self._parse_and_execute(process, wps_request, uuid)
        finally:
            #os.chdir(olddir)
            pass
`

**Comment by kvold** [comment]
Hi, I did something similar. I hardcoded in the path to the olddir:
```
finally:
    try:  # changing to olddir can fail, hardcoded path as temp fix
        os.chdir(olddir)
    except:
        oc.chdir('/usr/local/wps')
```

**Comment by SvenDowideit** [comment]
I'm hitting this too - and in poking around, it seems to me the root problem is that the code is doing an `os.chdir` at all - for example, https://stackoverflow.com/questions/12081789/pythons-working-directory-when-running-with-wsgi-and-apache

**Comment by ldesousa** [comment]
Thank you for this contribution, and apologies for how long it took to merge.

**Comment by SvenDowideit** [comment]
@ldesousa awesome!
