### ISSUE TITLE
async requests don't work with sqlite memory database

### ISSUE THREAD

**Issue by elemoine** [geopython/pywps#245]
I've been trying to use async requests (i.e. requests with `storeExecuteResponse`). And I realize that they don't work when an SQLite memory database is used. With an SQLite memory database is used I think the process forked to execute the WPS process gets its own copy of the memory database. So the UPDATE indicating the completion of the process is not seen by the WPS Service process. And because of that the WPS Service will end up queueing requests in the database and eventually rejecting all the requests when `maxprocesses` is reached.

Is this a known issue? What is recommended for async requests? Using an SQLite file database? Something else?

**Comment by jachym** [comment]
@elemoine it's known to me, that sqlite driver is rather unstable and therefore I recommend to use postgres. But your description is giving me some insights of what is really happening.

I personally do not have any strong opinion about this - we need database for logging and running job management, sqlite is file based and does not handle concurency well, I suggest, to use postgres.

Does it answer your question? Do you have some proposal how to overcome this?

**Comment by elemoine** [comment]
I did try Postgres but the SQLAlchemy `BLOB` type used for storing requests doesn't work with Postgres. So at this point my best hope is to use SQLite in file mode.

And no, I have no proposal. But I think it should be documented that PyWPS does not work with SQLite in memory. And I also think that this mode should not be the default. Finally, I'd recommend supporting PostgreSQL.

**Comment by jachym** [comment]
Should be fixed by #268

**Comment by elemoine** [comment]
@jachym have you verified that #268 actually fixes that issue? I have doubts, but I haven't checked myself.
