### ISSUE TITLE
Pywps4 fails if the url in @xlink:href contains a "="-sign

### ISSUE THREAD

**Issue by kvold** [geopython/pywps#248]
# Description
Pywps4 fails if the URL in xlink:href contains a "="-sign.

WPSRequest.py ( line 545: (attribute, attr_val) = attr.split('=') ) tries to split the href-attribute on the "="-symbol, but it hasn't set a max-occurrence. This causes it to fail when the url itself contains a "="-symbol since it expects two variables but receives three.

Can be fixed by setting maxsplit to 1 like this:
attr.split('=', 1)

# Environment

- operating system: Centos7
- Python version: 3.4.5
- PyWPS version: 4.0.0
- source/distribution
 - [X ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [X] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
Run a process which fetches a resource from a url, the url you're fetching from needs to contain "=".
Example:
http://localhost/wps?request=Execute&service=WPS&version=1.0.0&identifier=elevationXML&datainputs=gpx=@xlink:href=https://www.tromsatlas.no/WebServices/client/ElevationProfile.asmx/Download?gpxFile=test2.gpx

# Additional Information
Errorlog:
[Wed Mar 29 10:24:01.501701 2017] [wsgi:error] [pid 20084] --- Logging error ---
[Wed Mar 29 10:24:01.501761 2017] [wsgi:error] [pid 20084] Traceback (most recent call last):
[Wed Mar 29 10:24:01.502440 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/logging/__init__.py", line 978, in emit
[Wed Mar 29 10:24:01.502453 2017] [wsgi:error] [pid 20084]     msg = self.format(record)
[Wed Mar 29 10:24:01.502493 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/logging/__init__.py", line 828, in format
[Wed Mar 29 10:24:01.502502 2017] [wsgi:error] [pid 20084]     return fmt.format(record)
[Wed Mar 29 10:24:01.502535 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/logging/__init__.py", line 573, in format
[Wed Mar 29 10:24:01.502543 2017] [wsgi:error] [pid 20084]     record.exc_text = self.formatException(record.exc_info)
[Wed Mar 29 10:24:01.502575 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/logging/__init__.py", line 523, in formatException
[Wed Mar 29 10:24:01.502583 2017] [wsgi:error] [pid 20084]     traceback.print_exception(ei[0], ei[1], tb, None, sio)
[Wed Mar 29 10:24:01.502814 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/traceback.py", line 169, in print_exception
[Wed Mar 29 10:24:01.502827 2017] [wsgi:error] [pid 20084]     for line in _format_exception_iter(etype, value, tb, limit, chain):
[Wed Mar 29 10:24:01.502866 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/traceback.py", line 146, in _format_exception_iter
[Wed Mar 29 10:24:01.502874 2017] [wsgi:error] [pid 20084]     for value, tb in values:
[Wed Mar 29 10:24:01.502921 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/traceback.py", line 125, in _iter_chain
[Wed Mar 29 10:24:01.502931 2017] [wsgi:error] [pid 20084]     context = exc.__context__
[Wed Mar 29 10:24:01.502966 2017] [wsgi:error] [pid 20084] AttributeError: 'NoneType' object has no attribute '__context__'
[Wed Mar 29 10:24:01.502983 2017] [wsgi:error] [pid 20084] Call stack:
[Wed Mar 29 10:24:01.504186 2017] [wsgi:error] [pid 20084]   File "/usr/lib64/python3.4/site-packages/werkzeug/wrappers.py", line 291, in application
[Wed Mar 29 10:24:01.504206 2017] [wsgi:error] [pid 20084]     return f(*args[:-2] + (request,))(*args[-2:])
[Wed Mar 29 10:24:01.504224 2017] [wsgi:error] [pid 20084]   File "/usr/lib/python3.4/site-packages/pywps/app/Service.py", line 586, in __call__
[Wed Mar 29 10:24:01.504230 2017] [wsgi:error] [pid 20084]     request_uuid
[Wed Mar 29 10:24:01.504248 2017] [wsgi:error] [pid 20084]   File "/usr/lib/python3.4/site-packages/pywps/app/Service.py", line 306, in execute
[Wed Mar 29 10:24:01.504254 2017] [wsgi:error] [pid 20084]     response = self._parse_and_execute(process, wps_request, uuid)
[Wed Mar 29 10:24:01.504269 2017] [wsgi:error] [pid 20084]   File "/usr/lib/python3.4/site-packages/pywps/app/Service.py", line 330, in _parse_and_execute
[Wed Mar 29 10:24:01.504275 2017] [wsgi:error] [pid 20084]     inpt.identifier, inpt.identifier)
[Wed Mar 29 10:24:01.504289 2017] [wsgi:error] [pid 20084]   File "/usr/lib/python3.4/site-packages/pywps/exceptions.py", line 45, in __init__
[Wed Mar 29 10:24:01.504294 2017] [wsgi:error] [pid 20084]     LOGGER.exception(msg)
[Wed Mar 29 10:24:01.504311 2017] [wsgi:error] [pid 20084] Message: 'Exception: code: 400, locator: gpx, description: gpx'
[Wed Mar 29 10:24:01.504316 2017] [wsgi:error] [pid 20084] Arguments: ()

**Comment by tomkralidis** [comment]
@kvold can you provide an example of how to reproduce this issue?

**Comment by kvold** [comment]
@tomkralidis Done

**Comment by tomkralidis** [comment]
Thanks @kvold.  Fixed in #251
