### ISSUE TITLE
Feature: job scheduler extension

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#277]
# Description

This is a request for an optional extension to PyWPS to delegate job execution to a batch scheduler system like Slurm, Grid Engine and Torque.

# Additional Information

A prototype was already developed in PR #271 ... this PR will be refactored according to the PyWPS contribution guide lines.

**Comment by cehbrecht** [comment]
Added a PR #278 for this extension. The pull request contains an update of the PyWPS documentation on how to use and enable this extension.

There is docker demo available with a PyWPS and Slurm docker container:
https://github.com/bird-house/birdhouse-playground/tree/master/docker/pywps-scheduler-demo

See also conversation on pywps mailing list:
https://lists.osgeo.org/pipermail/pywps-dev/2017-June/001098.html

**Comment by cehbrecht** [comment]
I have replaced PR #278 by PR #296, which is an updated version of the scheduler extension and has a unittest for the new processing module.

The docker demo with Slurm is now here:
https://github.com/bird-house/birdhouse-docker-images/tree/master/pywps-scheduler-demo

There is also one for GridEngine:
https://github.com/bird-house/birdhouse-docker-images/tree/master/pywps-gridengine-demo

**Comment by tomLandry** [comment]
Cool stuff @cehbrecht.

**Comment by jorgejesus** [comment]
PR approved and close
