### ISSUE TITLE
Provide a mechanism for process debugging without running a PyWPS instance

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps#282]
In order for the user to debug a process, the ideal way is to provide a simple mechanism to run it independently, with passing through an active PyWPS instance (and therefore detaching execution into a different process). By remaining in the same OS process the user can apply a debugger, run the process from the Python console and use the traditional debug-by-print method.

To do so, the Process class can provide a method that pre-sets Request and Response objects. These objects can then be used for an ad-hoc invocation of the _handler() method. An example for the example Process class:

```
if __name__ == "__main__":
    sleep = Sleep()
    (request, response) = sleep.build_request_response()
    request.inputs['delay'][0].data = 10
    sleep._handler(request, response)

    assert response.outputs['sleep_output'].data == "done_slleping"
```

**Comment by jachym** [comment]
New version
```
def main():

    sleep = Sleep()
    (request, response) = sleep.build_request_response()
    literal_in  = sleep.__init__.inputs["delay"].copy()
    literal_in.data = 10
    request.inputs["delay"].push(literal_in)
    sleep._handler(request, response)

    assert response.outputs["sleep_output"].data == "done_sleeping"

if __name__ == "__main__":
    main()
```
