### ISSUE TITLE
ImportError: No module named flufl.enum (unittests)

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pywps#292]
# Description

The pythin module flufl.enum is necessary for running unittests. The module is sometimes not presents.

# Environment

- operating system:
- Python version:
- PyWPS version:
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

No problem on OsGEO. Only in clean VM

# Additional Information
Simple resolution to add to requirements-dev.txt

**Comment by jorgejesus** [comment]
Need to run 
pip install flufl.enum

Add flufl.enum too requirements.txt

**Comment by tomkralidis** [comment]
Fixed in https://github.com/geopython/pywps/commit/8c72874b433939b70ff6f45daa33da8bbf30da57
