### ISSUE TITLE
Implement ows:Keywords in Process  

### ISSUE THREAD

**Issue by huard** [geopython/pywps#293]
The WPS2.0 standard has a "ows:Keywords" field for processes that does not seem to be exposed in the current develop branch. 

We're in the process of building a library of climate-related functions based on pywps and we'll eventually want to parse the processes description to find which match user search criteria. In this context, having a "keyword" field would be really useful.

**Comment by jachym** [comment]
Hi,
the keywords should be supported for PyWPS-4 I believe ?

**Comment by huard** [comment]
Do you mean "they should already be supported" or "they will be supported" ? If this is something that can be done by a newbie, I could try to put together a PR.

**Comment by jachym** [comment]
#. There is support for keywords on service level as described http://pywps.readthedocs.io/en/master/configuration.html#metadata-main
But in general, you are more then right, we do lack support for Keywords for processes. I'm setting this ticket to higher priority.  WPS 1.0.0 should cover it - or do you need more, than it is in the spec?

**Comment by huard** [comment]
No, the spec is just fine. Thanks !

**Comment by jachym** [comment]
Oh, sh***t, sorry, I've double checked and it really seems, `Keywords` are not part of OGC WPS 1.0.0 standard, except for Capabilities response.

Well, another reason to move forward. Will move the discussion to mailing list.

**Comment by huard** [comment]
Got it. No problem.

**Comment by cehbrecht** [comment]
@huard @jachym 
We talked about it at the OGC coding-sprint in Bonn. We accept the keywords also for WPS 1.0.0 as a useful optional feature ... and one step into the direction of WPS 2.0.0.

Fixed by PR #306.

**Comment by huard** [comment]
Excellent, we'll start using the feature on our end. Thanks !
