### ISSUE TITLE
How to use format of complex output parameters

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#297]
# Description

The WPS protocol allows you to specify several output formats (mime-types) for a single output parameter. When your process executes you would like to set the output format to a specific one.

Example: allowed formats are PDF and PNG,  in your process you return an output as PDF.

In PyWPS you can set the `output_format` of an output parameter ... but it looks like it has no effect.

Was it intended in that way? Maybe we need to fix it.

# Additional Information

Example process where I set the output format depending on the input:
https://github.com/bird-house/emu/blob/master/emu/processes/wps_inout.py#L142

**Comment by gschwind** [comment]
Hello,

You can set the mime type of an output format with something like:
response.outputs['result'].data_format = pywps.inout.formats.Format(result_mimetype)
response.outputs['result'].set_file("out.csv")

Best regards

**Comment by cehbrecht** [comment]
@gschwind 
you are right, I need to use the `data_format` method instead of `output_format`. This has probably changed at some point. 

But ... doing so leads to exceptions. I have figured them out and fixed things in patch #314 .

**Comment by tomkralidis** [comment]
Fixed in #314
