### ISSUE TITLE
New Feature: return multiple output files via a reference document (json)

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#298]
# Description

In our projects we have quite often the case where a process produces multiple output files ... not knowing the number in advance and it could be many (10, 100). The WPS protocol allows us only to define an output parameter which returns a single output file reference. Unlike for the WPS input parameter one can not  define a multiplicity (min_occurs, max_occurs).

Our current workaround is not so nice ... we tar/zip the output files and return a reference to the archive.

A nicer approach could be as follows:

* output files are written to a folder in the storage (file storage currently).
* output folder name could be a uuid.
* a json document is generated with URL references to all files in the output storage.
* the json document could include metadata, which is usually part of an output parameter (title, abstract, mime-type).
* this json document is returned via a "normal" WPS output parameter (reference document, "virtual link").
* to make the special use of this json reference document recognizable by WPS clients, one could either have a special mime-type (are these kinds of documents already used somewhere?) or ... one could use `ows:Metadata` to indicate the semantic of the output parameter.

What do you think? 

I would like to collect some feedback first ... the implementation could be made by us.

# Additional Information

COWS WPS has implemented something similar ... it returns an XML document with references including additional metadata.

An example (under development) for a json reference document:
https://github.com/Ouranosinc/flyingpigeon/blob/spatial-op-wfs-opendap/flyingpigeon/handler_common.py#L114

Another example, which uses pywps code ... but it is not working that way ... but you may get the idea:
https://github.com/bird-house/emu/blob/master/emu/processes/wps_multiple_outputs.py

**Comment by cehbrecht** [comment]
We talked about it at OGC coding-sprint in Bonn and I will make a small extension to PyWPS 4.x to return a json file for multiple outputs.

**Comment by huard** [comment]
One proposal is to use the MetaLink standard. 
https://en.wikipedia.org/wiki/Metalink
I suppose we would add a jinja template for a metalink file. 

In terms of implementation, it's not clear to me how this should be done, as all the architecture is built on the assumption of "one output = one file". The "data" of a metalink output is the XML code, not the data of the individual files.

**Comment by tomLandry** [comment]
We have a somewhat similar requirement for the Canadian climate data portal. So I would say it's important to keep track of this.

**Comment by cehbrecht** [comment]
There is now a prototype implementation for metalink by @huard:
https://github.com/huard/pywps/tree/fix-298

I have added an example to emu using the current prototype:
https://github.com/bird-house/emu/blob/dev-mutliple-outputs/emu/processes/wps_multiple_outputs.py

**Comment by cehbrecht** [comment]
@huard ... collecting comments on fix-298 branch:
* output metalink document should have an extension, like `.xml`
* generated output file names should be more readable ...
* do we want that all files in a metalink document have the same mime-type?
* probably we want to add the mime-type for each document in a metalink document.
* ...

**Comment by cehbrecht** [comment]
@huard I find it a bit confusing that the `output` parameter changes when it is a metalink. Example:
```
response.outputs['output'].data = 'single output text
```

becomes

```
response.outputs['output']['one'].data = 'output text one'
response.outputs['output']['two'].data = 'output text two'
```

Could we change it to something else? Like:

```
response.outputs['output'].collection['one'].data = 'output text one'
```

**Comment by huard** [comment]
All good points. 

- For the extension, the wikipedia page suggests .metalink and .meta4  as extensions (https://en.wikipedia.org/wiki/Metalink) I could not find another reference for this. Open to change it to xml. 
- I'm using existing file naming mechanisms, so maybe we should open another ticket for this. 
- No, I think we should have flexibility. Ideally, the mime-type of each file would be included in the description.  Not clear to me how to do this cleanly yet. 
- Normally it should inherit it's file property from the DataHandler class.

Yes, it's possible to change it to collections. 

My question at the moment for you would be: How far should pywps support the description of the metalink file content ? Should the MetaLink ComplexOutput object be preset with its collection of other ComplexOutput objects ? Should that content be included in describeprocess outputs ?

**Comment by cehbrecht** [comment]
@huard 

>     * For the extension, the wikipedia page suggests .metalink and .meta4  as extensions 

If it is recommend I would keep `.metalink`.

>     * Normally it should inherit it's file property from the DataHandler class.

It does ... about the files are not added to the collection (only one). As far as I remember.

> Yes, it's possible to change it to collections.

Don't know about the name `collection` ... just a first guess.

> My question at the moment for you would be: How far should pywps support the description of the metalink file content ?

I can't say at the moment. We can get the `metalink` implementation working first ... then we may worry about its description.

**Comment by huard** [comment]
The implementation may be dependent on the description. To be clear, when we define the metalink ComplexOutput in the process definition, do we include in the "collection" property the list of the other ComplexOutputs listed in the metalink file?

**Comment by cehbrecht** [comment]
@huard I have looked into the metalink. The easy part I have understood:
* `.metalink` is used for metalink 3.0
* `.meta4` is used for metalink 4.0 ... having a different XML schema.

Could we maybe introduce a `metalink` class which we use to collect the resources and which handles the metalink attributes (identifier, description, ...). We can then just keep the current
 pywps `input` classes. The `metalink` class needs to use the pywps storage to store the resources.

Not sure if you like this and if it answers your question ...

**Comment by huard** [comment]
Hum, no, it doesn't really answer my question ; ) I'll try to come up with code to clarify what I mean.

**Comment by cehbrecht** [comment]
What do you think about my question, haven a metalink helper class?

Something like this:
```
ml = Metalink()
ml.add_file(MetaFile(identifier='example', description='Just an example', urls=[])
response.outputs['metalink'].data =ml.data
```

My motivation is that I find the tuning of the pywps input classes for metalink confusing. By this we would have a clear split.

**Comment by huard** [comment]
Yes, that would be more elegant I think. 

But don't we need to create a ComplexOutput object for each member of of the output collection, so that they are properly stored ? That's mostly what my MetaHandler was doing.

**Comment by cehbrecht** [comment]
Well, we need to interfere with pywps storage ... and maybe our Metalink class can make use of the `ComplexOutput` class .. I can't say ... you have more insight now :)

I thought your original question was about how we provide the description of these "internal" metalink ComplexOutputs ... maybe in a `DescribeProcess` request? I can't say ... this could be a follow-up task. Being able to return a Metalink file would be a first step.

**Comment by huard** [comment]
My thought was precisely that formal ComplexInputs have all the information we need to document the internal links, and take care of storage. I'd like to to reuse that ideally. What that would mean is that when we define the process inputs, the MetaLink input specifies the other ComplexInputs it's going to store.

**Comment by cehbrecht** [comment]
> My thought was precisely that ComplexInputs have all the information we need to document the internal links, and take care of storage. I'd like to to reuse that ideally.

Yes.

> [..] What that would mean is that when we define the process inputs, the MetaLink input specifies the other ComplexInputs it's going to store.

I don't get it :)

Currently we just use Metalink for outputs. Do you want to use the `ComplexOutput` class to define the Metalink outputs? I think that could happen internally in the Metalink class.

**Comment by huard** [comment]
Sorry, I meant output. 

I mean that at some point the process is going to specify
```outputs = [ComplexOutput('metalink', "Metalink file", supported_formats=[FORMATS.METALINK,]), ]```
But it would be nice if we found a way to say that the metalink itself will include a list of
```ComplexOutput('resource', 'NetCDF output', supported_formats=[FORMATS.NETCDF,])```
so we can use the identifier, title and abstract of those objects to feed into the metalink description.

**Comment by cehbrecht** [comment]
> But it would be nice if we found a way to say that the metalink itself will include a list of
> 
> ```
> ComplexOutput('resource', 'NetCDF output', supported_formats=[FORMATS.NETCDF,])
> ```
> 
> so we can use the identifier, title and abstract of those objects to feed into the metalink description.

Yes, I agree. My first guess would be to use the `ComplexOutput` internally in the `Metalink` class. The `Metalink` class itself has an interface that fits to the metalink declaration.

**Comment by huard** [comment]
@cehbrecht I just updated the branch with some of your suggestions. WIP.

**Comment by lhcorralo** [comment]
Hello!

Maybe it is a dumb question (sorry if it is so), but at the moment I am using the naive "add everything in a single zip" workaround, as I could not find any example json with multiple outputs. I would like to know how to use this feature, and if the output of a workflow may be a combination of the outputs of different workflow's steps.

Thanks in advance!

Luis

**Comment by huard** [comment]
Hi Luis, 
I don't think this was implemented as the issue name suggests. The solution that was implemented is to write an XML using the Metalink format.
