### ISSUE TITLE
pip package install gives error Service error: (sqlite3.OperationalError) unable to open database file

### ISSUE THREAD

**Issue by jorgejesus** [geopython/pywps#305]
# Description
Using pip install we have an old bug being reported

line 105, in connect
    return dialect.connect(*cargs, **cparams)
  File "/usr/local/lib/python3.5/dist-packages/sqlalchemy/engine/default.py",
line 393, in connect
    return self.dbapi.connect(*cargs, **cparams)
sqlite3.OperationalError: unable to open database file

The bug was reported on the mailing list 
[Pywps-dev] pywps demo: Service error: (sqlite3.OperationalError) unable to open database file

# Environment
Linux
- operating system:
- Python version:
2.7
- PyWPS version:
4.0.0
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [x] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
Install using  pip
# Additional Information

The pip package needs to be updated since this in an old bug

**Comment by jachym** [comment]
So, if I understand correctly, the bug is fixed? Releasing PyWPS 4.1 would do the job? @jorgejesus

**Comment by ldesousa** [comment]
@jorgejesus will ask permissions from @jachym for other committers to upload pip packages. In principle this issue is solved in the latest HEAD.

**Comment by cehbrecht** [comment]
See also #353.

**Comment by cehbrecht** [comment]
I consider this as done.
