### ISSUE TITLE
Bug with stored jobs of different types

### ISSUE THREAD

**Issue by elemoine** [geopython/pywps#308]
# Description

I think we've found a major bug in PyWPS. The bug occurs when mixing jobs of different types, and when jobs are stored because `maxparallel` is reached.

Let's say the PyWPS application defines two processes, i.e. two subclasses of `pywps.app.Process`: `ProcessA` and `ProcessB`. Let's also say that `maxparallel` is `2`, meaning that there's never more than 1 async job running at a given time.

Now consider this sequence:

1. Launch a ProcessA job in async mode
2. Launch a ProcessB job in async mode before the 1st job is finished

What will happen is the following:

An OS process is forked for the first job (the `ProcessA` job). The second job (the `ProcessB` job) is stored in the database queue because there already is a job running. When the first job's `handler` function completes, the `_run_process` function [checks](https://github.com/geopython/pywps/blob/3f2e6c63e6cf9d9cd0ad6e690271259205e57ae6/pywps/app/Process.py#L272) if the job queue has elements. So, in our case, `_run_process` gets the `ProcessB` job from the queue, and [schedules](https://github.com/geopython/pywps/blob/3f2e6c63e6cf9d9cd0ad6e690271259205e57ae6/pywps/app/Process.py#L285) its execution. The issue is that the `ProcessB` job will be executed using `ProcessA`'s handler! 

# Environment

- operating system: Linux
- Python version: 3.4
- PyWPS version: current develop branch
- source/distribution
 - [X] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [X] other (please specify): uWSGI

# Steps to Reproduce

See the description.

# Additional Information

**Comment by ldesousa** [comment]
Fixed in PR #312
