### ISSUE TITLE
Create test(s) for PR #334

### ISSUE THREAD

**Issue by ldesousa** [geopython/pywps#335]
# Description

@pesekon2 kindly contributed a new feature that lets the GRASS be set by a complex input. However, this new feature is not covered in the tests.

**Comment by jachym** [comment]
@pesekon2 that would be awesome.

you have to prepare unit test in the tests directory

the travis file is configuration for travia servixe we use for continuous integration

**Comment by landam** [comment]
@pesekon2 Do you have time for that, BTW? Thanks.
