### ISSUE TITLE
rewrite output generation using jinja2

### ISSUE THREAD

**Issue by jachym** [geopython/pywps#337]
# Description

Currently, we are generating output XML responses using `lxml` generation facility. This is no longer possible, since the difference between WPS 2.0.0 and 1.0.0 are relatively big and we need to separate the logic (model) from the representation (view).

I therefore suggest, we introduce templating system again, and this time it should be well know 
http://jinja.pocoo.org/

Each version should have it's own directory with templates. This should also lead to major code simplification.

**Comment by jachym** [comment]
The work is happening here https://github.com/jachym/PyWPS/tree/templates

**Comment by ldesousa** [comment]
Sounds like a sensible approach.

**Comment by cehbrecht** [comment]
I also would prefer using a template engine. There are several ones available for Python. Jinja seems currently to be the favorite one. Jinja is also used by Ansible.

**Comment by jachym** [comment]
It's used in Django too. License is BSD, so we should be fine

**Comment by cehbrecht** [comment]
done with PR #345.
