### ISSUE TITLE
Can we make gdal an optional dependency?

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#340]
# Description

I'm currently creating a conda package and I see the **long** list of dependencies that needs to be pulled. This is probably caused by the `gdal` dependency. I haven't checked where it is used in `pywps` but I suppose it is not an essential dependency. 

Could we make `gdal` an optional dependency? The conda (Python) package would be more lightweight then and less likely to conflict with others. Installations that need `gdal` functionality can install it in a second step. 

# Additional Information

pywps conda package: #234.

**Comment by jachym** [comment]
as @ldesousa is writing, it's "just" for the validator

even though, input data validation is one of pywps-4 key features (imho)

**Comment by ldesousa** [comment]
@jachym I say "just" because it is "only" for .tif files. In any case, we are not removing functionality, just making it optional.

**Comment by cehbrecht** [comment]
It is not an urgent thing to do but I can change the code to make `gdal` on optional dependency. Then I can add a `requirements-minimal.txt` without `gdal` ... the default `requirements.txt` adds `gdal` to it. I will then use the "minimal" requirements to build the conda package. In the documents I can describe how to install the optional packages to enable more features ... with conda it is an easy thing to install `gdal` but it is a "heavy" dependency.

Oops ... just checked the current `requirements.txt`. Looks like `gdal` is already optional :) So, I will figure out and let you know :).

**Comment by cehbrecht** [comment]
This was false alarm ... already done in #86.

I will update the conda package accordingly.
