### ISSUE TITLE
Add url property to IOHandler

### ISSUE THREAD

**Issue by huard** [geopython/pywps#352]
# Description

In addition to file, memory_object, stream and data, add a url property to IOHandler class to facilitate handling of remote access data protocols.

**Comment by cehbrecht** [comment]
This is related to OpenDAP handling (#152). See also discussion in PR: https://github.com/bird-house/pywps/pull/1

**Comment by cehbrecht** [comment]
The URL property makes sense when we want to support OpenDAP (and other data service protocols). Otherwise we would misuse the `file` property.

See also the discussion in PR https://github.com/bird-house/pywps/pull/2

**Comment by huard** [comment]
I have a question about ComplexOutputs. 

If the output source type is file, and as_reference is True, the output file will be copied over the outputpath (by FileStorage) and the server will send back the url to this file. 
If the output source type is file and as_reference is False, the _json_data tries to parse the file (not sure I understand why it assumes that it is an xml file), and if that fails, it sends back the text or bytes. 

Now what should happen if the source_type is url ? My assumption would be that if as_reference is True, then only the href is sent back, but if as_reference is False, then it would download the href and extract the data. Correct ?

**Comment by cehbrecht** [comment]
> Now what should happen if the source_type is url ? My assumption would be that if as_reference is True, then only the href is sent back, but if as_reference is False, then it would download the href and extract the data. Correct ?

Yes, I would expect the same behavior. I haven't checked but this is already taken care of?

**Comment by huard** [comment]
Yes, in the last commit.
