### ISSUE TITLE
Upload new version to PyPI 

### ISSUE THREAD

**Issue by eran-pinhas** [geopython/pywps#353]
# Description
The latest version `.egg` was updated 19 months ago on Dec '16. 
The latest version `.whl` was updated on Jun '17.

**Comment by cehbrecht** [comment]
Probably we want to upload pywps after the 4.2.0 release (hopefully after FOSS4G in Portugal). 

Currently I help myself with using a conda package with the latest code:
https://anaconda.org/birdhouse/pywps

@eran-pinhas 
You can also `pip install` from github master.

**Comment by gamesbook** [comment]
Any follow-up?  Its been 4 months since the conference referred. A stable updated pyWPS release on pypi.org would be very welcome!

**Comment by cehbrecht** [comment]
+1 for making a release of the current state.

@jachym what do you think?

**Comment by tomkralidis** [comment]
FYI I've updated PyPI with the latest PyWPS release (4.2.0) which was released on 2018-12-17.

Let us know if this issue can be closed or needs further discussion.

**Comment by eran-pinhas** [comment]
looks great, closing the issue. Thank you

opening for discussion: will it be possible to publish it continuously using the travis pipeline?
