### ISSUE TITLE
optional metadata href+role is missing in jinja templates

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#362]
# Description

With PR #345 new templates using jinja where introduced. The optional Metadata href and role attributes are not part of these templates. This PR will fix this.

See `Metadata` class: 
https://github.com/geopython/pywps/blob/abdd4a3f01404e98d2d1705663537f9c2d1e5552/pywps/app/Common.py#L11

**Comment by jachym** [comment]
Done, thank you
