### ISSUE TITLE
automatic tests: coveralls complains

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#367]
# Description

We have configured coveralls checks, which are not happy with us:
https://coveralls.io/builds/18259291 

I would see this more as a warning ... but the tests are marked as failed. Maybe we can configure it to behave more nicely.

In other projects I'm using [codacy](https://www.codacy.com/) for automatic code reviews. It is not only for the statistics ... it discovers also potential bugs and security issues.

**Comment by jachym** [comment]
maybe we should call for PSC meeting and discuss all the things for 4.2

**Comment by Zeitsperre** [comment]
@cehbrecht If you're interested, I can submit a proposal relatively qeuickly to fix this.

**Comment by cehbrecht** [comment]
> @cehbrecht If you're interested, I can submit a proposal relatively quickly to fix this.

@Zeitsperre sounds good. go ahead 👍
