### ISSUE TITLE
Using six to handle Python 2.7/3.x compatibility

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#369]
# Description

I would prefer to use [six](https://pythonhosted.org/six/) to handle Python 2/3 compatibility. 

# Additional Information

See also: https://github.com/geopython/OWSLib/issues/478

**Comment by SvenDowideit** [comment]
#477 suggests this isn't necessary :)

**Comment by cehbrecht** [comment]
@SvenDowideit right. closed.
