### ISSUE TITLE
test_assync fails

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#388]
# Description

When you run the tests with `pytest` then `test_assync` fails:

```
$ pytest tests/test_assync.py

ImportError while importing test module '/Users/pingu/Documents/GitHub/birdhouse/pywps/tests/test_assync.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_assync.py:9: in <module>
    from pywps import WPS, OWS
E   ImportError: cannot import name 'WPS'
```

This does not happen when you run the test suite with (like on travis):
```
$ python -m unittest tests
```

`test_assync` has no `load_tests` method ... maybe intentionally. But probably we should do something about it (add `load_tests` but also a `skip`, or fix the test).

# Steps to Reproduce

Run:
```
$ pytest tests
```

# Additional Information

**Comment by jachym** [comment]
Thanks @cehbrecht
