### ISSUE TITLE
gdal setup on travis sometimes fails

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#398]
# Description

... maybe we can simplify the Travis setup by using a Conda environment? 

Currently I only use pywps with Conda.

# Steps to Reproduce

# Additional Information

**Comment by Zeitsperre** [comment]
GDAL/OGR is dependent on a few C libraries that require installation (or building) in order to run. I can see that the version is pegged to 2.1.0 (which is deprecated). Is there any interest in using the `GDAL_VERSION` env var instead to pull the actual gdal?

Does PyWPS currently install against GDAL3?

**Comment by cehbrecht** [comment]
@Zeitsperre `GDAL_VERSION` is part of travis? We can use it to ease the travis installation. GDAL/OGR is only used by the validator. We should update it to the latest version. What you like to do this?

**Comment by cehbrecht** [comment]
gdal is an issue again ... now on GitHub CI, see PR #580:

GitHub CI is using `ubuntu-latest` which is now using `gdal=3`. 
Workaround in CI test is currently to use Test CI `ubuntu-18.04`

In our conda env we skip gdal ... it is optional:
https://github.com/conda-forge/pywps-feedstock/blob/master/recipe/meta.yaml

**Comment by Zeitsperre** [comment]
We could specify a build recipe for `pip` that pulls in GDAL and other geospatial libraries, but that would necessitate disabling some example processes. I'm not sure how you feel about that. From what I understand, even without the examples, GDAL is still needed, right?

It's interesting that the PyWPS conda recipe is so bare. I don't know if any of the listed libraries use GDAL in their requirements. Perhaps GDAL is unneeded ?

**Comment by cehbrecht** [comment]
> It's interesting that the PyWPS conda recipe is so bare. I don't know if any of the listed libraries use GDAL in their requirements. Perhaps GDAL is unneeded ?

GDAL is optional ... but used at some places. I would prefer to remove it in pywps ... but maybe there are reasons against this.

ping @jachym

**Comment by Zeitsperre** [comment]
Ultimately, the complication with GDAL has to do with the fact that it needs to have a *corresponding* version between the C and Python libraries, and `pip` is designed to install the *newest* version. Just a thought, but what if we were to pull the installed version with a command like this:
```
apt-get install libgdal-dev
GDAL_VERSION=$(gdal-config --version)
pip install gdal==$GDALVERSION
```

**Comment by huard** [comment]
@cehbrecht @jachym 

This is causing a CI failure for my latest PR.
