### ISSUE TITLE
BoundingBox input via execute url

### ISSUE THREAD

**Issue by drlferreira** [geopython/pywps#404]
# Description

Hello there,

I am not able to find what is the string to put as input in the bounding box input (execute request). 

Thank you for your time :)

**Comment by cehbrecht** [comment]
BoundingBox example from the WPS 1.0.0 spec for GET request:
```
bboxInput=46,102,47,103,urn:ogc:def:crs:EPSG:6.6:4326,2
```

**Comment by cehbrecht** [comment]
bbox `get` request fixed by #551
