### ISSUE TITLE
User defined exceptions?

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#406]
# Description

I'm coming back to the discussion in PR #386. Currently PyWPS shows only a common WPS exception when an error has occurred ("_Please check the logs ..._"), introduced in PR #357.

A WPS exception is a way to communicate to the user ... we like to give some hints when something goes wrong. Though we don't want (or should not) show the raw traceback which is probably not understandable for the end-user and a potential security risk.

Could we introduce a new "User Exception"? 

In the process implementation we could through this user exception intentionally do give the user some hints of what might have gone wrong ("_No data found for given selection parameter ..._"). We could add restrictions to the user exception type, like only 300 chars, no suspicious characters (no tracebacks), ... In all other cases the common exception will be thrown ("_Check the logs_").

@jachym @huard 
What do you think?

# Environment

- operating system:
- Python version:
- PyWPS version:
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

See discussion in PRs #386, #357.

Also we need to check the Python encodings: #233, #400.

**Comment by huard** [comment]
Seems reasonable.

**Comment by jachym** [comment]
I'm all for it - as long as we manage to return back valid WPS [1,2].x XML document
