### ISSUE TITLE
GRASS process fails when using existing location

### ISSUE THREAD

**Issue by landam** [geopython/pywps#408]
# Description

PyWPS GRASS processes based on existing GRASS location fails with

```
ERROR: Variable 'LOCATION_NAME' not set
Traceback (most recent call last):
  File "/tmp/pywps-master/local/lib/python2.7/site-packages/pywps/app/Process.py", line 193, in _run_process
    self._set_grass(wps_request)
  File "/tmp/pywps-master/local/lib/python2.7/site-packages/pywps/app/Process.py", line 367, in _set_grass
    location=location)
  File "/usr/lib/grass74/etc/python/grass/script/core.py", line 421, in run_command
    return handle_errors(returncode, returncode, args, kwargs)
  File "/usr/lib/grass74/etc/python/grass/script/core.py", line 332, in handle_errors
    returncode=returncode)
CalledModuleError: Module run None ['g.mapset', '-c', 'mapset=pywps_mapset', 'location=grass_location', 'dbase=/tmp'] ended with error
Process ended with non-zero return code 1. See errors in the (error) output.
```

# Environment

- operating system: Linux
- Python version: 2.7
- PyWPS version: master
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): flask demo

# Steps to Reproduce

Tested on grassbuffer.py from PyWPS-Flask demo with small modification:

```
           grass_location="/tmp/grass_location"
            # grass_location="epsg:3857"          
```

# Additional Information

Probably cased by #334.

**Comment by jachym** [comment]
maybe the mapset name should be some random mapset  name? not only `pywps_mapset` - imagine, there would be two concurent processes running on the same location ?

**Comment by pesekon2** [comment]
@jachym Good point. New commit added to PR #414.

**Comment by jachym** [comment]
@pesekon2 just 2 small comments
