### ISSUE TITLE
ComplexOutput as data does not always work

### ISSUE THREAD

**Issue by huard** [geopython/pywps#412]
# Description

When as_reference is False in a ComplexOutput, but the content is provided with the file attribute, no data is included in the response, only the reference. 

When the content is provided by the data attribute, then the data is sent, but includes HTML escape characters and CDATA statements. Is this expected? 

# Environment

- operating system: ubuntu
- Python version: 3.6
- PyWPS version: master
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
Tweak emu/emu/processes/wps_multiple_outputs.py to set as_reference to False for both ComplexOutputs. Then run emu/tests/test_wps_multiple_outputs.py and inspect the output. 

# Additional Information
It seems these cases are not exercised by the test suite.

**Comment by cehbrecht** [comment]
fixed by PR #431.
