### ISSUE TITLE
Unable to build pyWPS

### ISSUE THREAD

**Issue by gamesbook** [geopython/pywps#422]
# Description

I am unable to build pyWPS inside a Docker.  The error is:
```
The 'jsonschema' distribution was not found and is required by pywps
```

# Environment

- operating system: Ubuntu 16.04
- Python version: 2.7
- PyWPS version: 4.0
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify):  nginx

# Steps to Reproduce

* Ran the following steps inside the Docker:

```
RUN apt-get -y update && apt-get -y upgrade && apt-get install -y \
    nginx-full \
    gunicorn \
    build-essential \
    libgdal-dev \
    gdal-bin \
    python \
    python-dev \
    python-setuptools \
    python-magic \
    python-lxml \
    python-gdal \
    python-flufl.enum

RUN git clone https://github.com/geopython/PyWPS.git; \
    cd ./PyWPS; \
    python setup.py install
```

Error trace:
```
Searching for jsonschema
Reading https://pypi.python.org/simple/jsonschema/
Best match: jsonschema 3.0.0a3
Downloading https://files.pythonhosted.org/packages/47/e1/afd760aa29665e61142811ef6ea8b8f79e43574ac8427473a11f6e918a10/jsonschema-3.0.0a3.tar.gz#sha256=dfd8426040892c8d0ef6da574085f282569f189cb24b70091a66c21c12d6705e
Processing jsonschema-3.0.0a3.tar.gz
Writing /tmp/easy_install-iSgbeL/jsonschema-3.0.0a3/setup.cfg
Running jsonschema-3.0.0a3/setup.py -q bdist_egg --dist-dir /tmp/easy_install-iSgbeL/jsonschema-3.0.0a3/egg-dist-tmp-q6_h16
/usr/lib/python2.7/distutils/dist.py:267: UserWarning: Unknown distribution option: 'use_scm_version'
  warnings.warn(msg)
warning: install_lib: 'build/lib.linux-x86_64-2.7' does not exist -- no Python modules to install

zip_safe flag not set; analyzing archive contents...
Moving UNKNOWN-0.0.0-py2.7.egg to /usr/local/lib/python2.7/dist-packages
Adding UNKNOWN 0.0.0 to easy-install.pth file

Installed /usr/local/lib/python2.7/dist-packages/UNKNOWN-0.0.0-py2.7.egg
error: The 'jsonschema' distribution was not found and is required by pywps
```
# Additional Information

**Comment by gamesbook** [comment]
It may be the issue that PyWPS has chosen to use the 3.0 alpha release of `jsonschema` rather the current stable release (2.6.0 at time of writing)?

**Comment by cehbrecht** [comment]
@gamesbook I usually use a conda environment for pywps and I didn't have troubles with conda.

I tried your example in a docker container and run into the same issue. I can't say what has gone wrong. But I installed `jsonschema` manually, and it worked after that:

```
$ easy_install pip
$ pip install jsonschema==3.0.0a3
$ python setup.py install
```

**Comment by gamesbook** [comment]
@cehbrecht Thanks, I ended up doing the same myself. I used 
```
pip install jsonschema==2.6.0
```
And it worked.  Ideally, I should *not* be building my project with a dependency on this git repo (which could be unstable), but from a stable release.  Unfortunately, the last release to PyPi was nearly 2 years ago ...
