### ISSUE TITLE
Add KML as a supported mimetype FORMAT

### ISSUE THREAD

**Issue by Zeitsperre** [geopython/pywps#423]
# Description
KML is a Google-developed and OGC-compliant container for vector and raster data (http://www.opengeospatial.org/standards/kml/). In defining my own WPS processes, I've been relying on the FORMATS entries as well as manually defining KML. It would be great if this format was added to the list by default.

# Additional Information

**Comment by cehbrecht** [comment]
fixed by PR #424.
