### ISSUE TITLE
provide 3.2.2 release to PyPI

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#46]
Given 3.2.2 is the current latest stable release, looks like PyWPS' [PyPI](https://pypi.python.org/pypi/pywps) presence is out of date.

- [x] upload 3.2.2 to PyPI
- [x] update http://pywps.org/download with PyPI link
- [x] ensure release process includes PyPI upload

**Comment by tomkralidis** [comment]
Added PyPI link to downloads page in https://github.com/geopython/pywps.org/commit/402d9ebed91541fe2848459fc17dd4faf53c3612 and updated https://github.com/geopython/pywps/blob/master/RELEASE.howto#L21

**Comment by jachym** [comment]
https://pypi.python.org/pypi/pywps published
