### ISSUE TITLE
os.stat_result has no attribute st_blksize on windows

### ISSUE THREAD

**Issue by omerlevko** [geopython/pywps#463]
# Description
when i execute a process in pywps-flask(on windows) i get an error (on topic)
the error stacktrace leads to https://github.com/geopython/pywps/blob/d90a12416fc0377d803409921ec1dae2f9cd6c05/pywps/inout/storage.py#L111

the error doesn't occurs on linux operating system.

# Environment

- operating system: windows 10
- Python version: 3.6.3
- PyWPS version: 4
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce
set up pywps-flask, run it and execute a process

# Additional Information

**Comment by michahashkes** [comment]
This has also been happening to me. Any updates?
Can anyone direct me and I'll try to fix it myself?

**Comment by cehbrecht** [comment]
The block size seems to work on linux only:
https://docs.python.org/3/library/os.html#os.stat_result.st_blocks 

I can't say how to make this work on windows. We probably don't won't to support windows for production use, only for development. So, if there is no better solution we may skip the "available disk space" check on windows.

**Comment by eran-pinhas** [comment]
> We probably don't won't to support windows for production use, only for development. So, if there is no better solution we may skip the "available disk space" check on windows.

Legit. I agree

**Comment by Zeitsperre** [comment]
Fixed with #476
