### ISSUE TITLE
Shall we skip Python 2.7 support?

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#477]
# Description

Supporting only Python 3.x makes the code easier to maintain. In `OWSLib` we have already done this step.

What is your opinion?

**Comment by ldesousa** [comment]
I agree. Python 2.7 is now being dropped from most Linux distributions, pretty soon no one will use it any more.

Let us keep the discussion open for now and have a PSC vote later in the month. Hopefully there will be quorum during FOSS4G.

**Comment by jachym** [comment]
Motion: get rid of Python 2 support for PyWPS 4.3 (future 4.4) branch

- [ ] @cehbrecht 
- [ ] @jachym
- [ ] @ldesousa 
- [ ] @tomkralidis 
- [ ] @jonas-eberle 
- [ ] @jorgejesus

**Comment by jachym** [comment]
done, thank you all
