### ISSUE TITLE
Scheduler extension not working

### ISSUE THREAD

**Issue by tommygod3** [geopython/pywps#480]
# Description
The scheduler extension (`mode = scheduler`) is not working.
Fails when job is dumped to file, at this line: https://github.com/geopython/pywps/blob/b34de655a0cac361b32c89c67fbb3dc74c4df99e/pywps/processing/job.py#L41

# Environment

- operating system: centOS7
- Python version: 3.7
- PyWPS version: 4.3
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [x] other (please specify): As part of [emu](https://github.com/bird-house/emu) installation
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): nginx

# Steps to Reproduce
Use `mode = scheduler` in configuration.

**Comment by cehbrecht** [comment]
solved by PR #482.
