### ISSUE TITLE
convert_anyURI uses pywps._compat.urlparse as a module

### ISSUE THREAD

**Issue by corrado9999** [geopython/pywps#486]
# Description
`convert_anyURI` calls [`pywps._compat.urlparse.urlparse`](https://github.com/geopython/pywps/blob/1f6aa6155289aabfbf714f8d43df00f8cc7cf544/pywps/inout/literaltypes.py#L288) instead of [`pywps._compat.urlparse`](https://github.com/geopython/pywps/blob/1f6aa6155289aabfbf714f8d43df00f8cc7cf544/pywps/_compat.py#L19)
# Environment

- operating system: Miniconda 3 @ CentOS Linux release 7.6.1810 (Core) 
- Python version: Python 2.7.16 |Anaconda, Inc.| (default, Mar 14 2019, 21:00:58) 
- PyWPS version: 4.2.1
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [x] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): N/A

# Steps to Reproduce
```
>>> pywps.inout.literaltypes as lt
>>> convert_anyURI("https://github.com")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/miniconda/envs/emage/lib/python2.7/site-packages/pywps/inout/literaltypes.py", line 241, in convert_anyURI
    components = urlparse.urlparse(inpt)
AttributeError: 'function' object has no attribute 'urlparse'
```
# Additional Information
The fix is very easy (change `urlparse.urlparse` to `urlparse`), not sure if you would like a pull request. Anyway, I noticed that [tests/test_literaltypes.py](https://github.com/geopython/pywps/blob/1f6aa6155289aabfbf714f8d43df00f8cc7cf544/tests/test_literaltypes.py#L13) does not test such data type. Perhaps something like
```
self.assertEqual(convert_anyURI("http://username:password@hostname.dom:port/deep/path/;params?query#fragment"),
                 ('http', 'username:password@hostname.dom:port', '/deep/path/', 'params', 'k=v', 'fragment')
                )
self.assertEqual(convert_anyURI("file:///very/very/very/deep/path"),
                 ('file', '', '/very/very/very/deep/path', '', '', '')
                )
```
may be enough?

**Comment by cehbrecht** [comment]
@corrado9999 Thanks for reporting. Would you like to add a PR? You can also update the tests.

**Comment by corrado9999** [comment]
When "testing the test" I got an unexpected error due to this [test](https://github.com/geopython/pywps/blob/1f6aa6155289aabfbf714f8d43df00f8cc7cf544/pywps/inout/literaltypes.py#L290)
```python
if components[0] and components[1]:
    return components
else:
    raise InvalidParameterValue(
        'The value "{}" does not seem to be of type anyURI'.format(inpt))
```
because, with a "file" schema, the netloc part of the URL (components[1] in the code) is always empty. Does it make sense to explicitly check for this schema and avoid to test the second component for it? Are there other schemas like that?

**Comment by cehbrecht** [comment]
@corrado9999 I would handle the `file` URL separate ... not sure if there are more cases.
