### ISSUE TITLE
Time for a release ?

### ISSUE THREAD

**Issue by huard** [geopython/pywps#488]
# Description

The last release dates from last December.

**Comment by ldesousa** [comment]
Looks like it, many commits since 4.2. Can someone gather a change log? In the meantime we need to set up a PSC meeting.

**Comment by cehbrecht** [comment]
I can update the change log.

**Comment by huard** [comment]
Thanks, this is really appreciated.

**Comment by jachym** [comment]
updated, closing, thank you
