### ISSUE TITLE
logging initialisation does not work for async processes

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#50]
when running an async process the logger does not log to the configured logfile. 

In `Pywps.setLogFile()`  method `logging.basicConfig()` is called according to the configuration. But in the async case somehow the logger has already a logging handler and calling `basicConfig()` has no effect. 

Patch #49 provides a workaround to remove logging handlers in the async case before calling `basicConfig()` 

See also #28.

**Comment by tomkralidis** [comment]
@cehbrecht #49 has been merged.  Should we close this issue?

**Comment by cehbrecht** [comment]
the workaround #49 works for me and the future is pywps-4.

**Comment by jachym** [comment]
thanks

st 10. 2. 2016 v 11:53 odesílatel Tom Kralidis <notifications@github.com>
napsal:
