### ISSUE TITLE
Question: plans to drop dependencies 'flufl.enum' and 'pathlib' from requirements?

### ISSUE THREAD

**Issue by Zeitsperre** [geopython/pywps#509]
# Description
I'm wondering if there are any plans to remove the flulf.enum and pathlib dependencies from the requirements for PyWPS. I've run into issues with installing PyWPS in conda environments using modern python version because of these libraries, which is odd since both of these libraries have been available in the standard library since version 3.4.

Is there a development branch for the PyWPS 4.3+ where Python2.7 and requirements not native to Python3 have been dropped from the requirements?

# Environment

- operating system: Linux
- Python version: 3.7
- PyWPS version: 4.2.3
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): Anaconda (conda-forge)

# Steps to Reproduce

# Additional Information

**Comment by cehbrecht** [comment]
@Zeitsperre I want to drop Python 2 support for the next release (see #477).

**Comment by cehbrecht** [comment]
Fixed by PR #520.
