### ISSUE TITLE
Wrong version

### ISSUE THREAD

**Issue by huard** [geopython/pywps#525]
# Description

Master still has `__version__` set to 4.2.2 even though it has been tagged with 4.2.4.

**Comment by tlvu** [comment]
`__init__.py` still hardcode `4.2.2` on head of branch `master`:

https://github.com/geopython/pywps/blob/61e03fe566d9a4cdf52a6b941a404916592e5aac/pywps/__init__.py#L12

**Comment by cehbrecht** [comment]
we don't use [bumpversion](https://pypi.org/project/bumpversion/) ... so we got these inconsistencies. Should we create a 4.2.x branch and fix the release, introduce bumpversion and make a 4.2.5 release?

ping @jachym

**Comment by cehbrecht** [comment]
> we don't use [bumpversion](https://pypi.org/project/bumpversion/) ... so we got these inconsistencies. Should we create a 4.2.x branch and fix the release, introduce bumpversion and make a 4.2.5 release?
> 
> ping @jachym

@huard @davidcaron do you agree?

**Comment by huard** [comment]
For us, bumpversion has simplified releases, so I would recommend its use in pywps. 

I don't think there is a rush for us to get a new version out, so this change could happen with the next planned release. 

@Zeitsperre Would you have time to submit a PR ?

**Comment by Zeitsperre** [comment]
@huard Sure. I can add something fairly easily.

**Comment by Zeitsperre** [comment]
@cehbrecht @huard feel free to weigh in on the PR. Also, I don't think I have privileges here; Think I could be added to the group if I'm not listed?

**Comment by cehbrecht** [comment]
@Zeitsperre I have send you an invitation for write access. I close this issue ... will use bumpversion for the next release (#527)
