### ISSUE TITLE
Add support for validating GPX-files

### ISSUE THREAD

**Issue by kvold** [geopython/pywps#535]
I was hoping it might be possible to add a validator for GPX-files to pywps. It's something that would be quite beneficial for our use-case (and hopefully many others).

It's a relatively low-hanging fruit as the validategml-function is practically a validategpx-function, just have to replace the GetName() == "GML" and the mimetype FORMATS-match.

If desired I can see about creating a pull-request (though I've had some issues getting the tests to run).

**Comment by cehbrecht** [comment]
Fixed by PR #537.
