### ISSUE TITLE
Source code in tagged versions does not match with committed code

### ISSUE THREAD

**Issue by laskama** [geopython/pywps#550]
# Description

When using the current master version, the SQLite functionality of pywps-flask seems to be broken.
I obtain the following error, when running the flask server and try to access getCapabilities for example:
```
2020-11-04 13:09:26,077] [ERROR] file=/Users/mariuslaska/PycharmProjects/pywps-flask/venv/lib/python3.6/site-packages/pywps/exceptions.py line=44 module=exceptions function=__init__ Exception: code: 500, description: No applicable error code, please check error log., locator: 
Traceback (most recent call last):
  File "/Users/mariuslaska/PycharmProjects/pywps-flask/venv/lib/python3.6/site-packages/sqlalchemy/engine/base.py", line 1277, in _execute_context
    cursor, statement, parameters, context
  File "/Users/mariuslaska/PycharmProjects/pywps-flask/venv/lib/python3.6/site-packages/sqlalchemy/engine/default.py", line 593, in do_execute
    cursor.execute(statement, parameters)
sqlite3.OperationalError: no such table: pywps_jobs
```
# Environment

- operating system: MacOS 10.10.5
- Python version: 3.6
- PyWPS version: 4.2.8
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [x] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [x] other (please specify): flask

# Steps to Reproduce

I came across this when forking the pywps repository and using it during installation of the pywps-flask demo. I replaced the `pywps` from the requirements file with `pywps @ git+https://github.com/geopython/pywps.git@master#egg=pywps`.  However, the sqlite logging database seems to be broken. This was already reported in an issue of the flask repository (https://github.com/geopython/pywps-flask/issues/55#issue-563271235), which was then closed since it was solved by reinstallation of the latest release.

# Additional Information

**Comment by cehbrecht** [comment]
@laskama The current releases 4.2.x are made based on the `pywps-4.2` branch:
https://github.com/geopython/pywps/tree/pywps-4.2

The `master` branch is still in development ... needs to be fixed.

The code on the `master` works different and the database need initialization:
* https://github.com/geopython/pywps/blob/master/docs/install.rst
* https://github.com/geopython/pywps/blob/master/docs/deployment.rst

**Comment by laskama** [comment]
Thanks for the quick reply and for clarifying my misunderstandings!
