### ISSUE TITLE
How to handle json dump for inputs with CDATA?

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#553]
# Description

When dumping (as json) a complex-input with format json then the data gets tagged with `CDATA`:
https://github.com/geopython/pywps/blob/9fa56cc17bf545a9a583271d83affa5b479d3373/pywps/inout/inputs.py#L243

Is this necessary?

This needs to be handled when loading the json dump again ... currently this is not the case.

See also #444.

# Environment

- operating system:
- Python version:
- PyWPS version: 4.2
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

We have a workflow process with a workflow document in json:
https://github.com/roocs/rook/blob/858130631bf0a37c19a78e8e94961b7159846833/rook/processes/wps_orchestrate.py#L13

The json document is send with the wps request ... not as reference.

When we use the pywps scheduler extension the `WPSRequest` is dumped as a json file:
https://github.com/geopython/pywps/blob/9fa56cc17bf545a9a583271d83affa5b479d3373/pywps/processing/job.py#L71

In this case the workflow document (json format) is tagged by `CDATA`:
https://github.com/geopython/pywps/blob/9fa56cc17bf545a9a583271d83affa5b479d3373/pywps/inout/inputs.py#L243

When the json dump is loaded the `CDATA` tag is still part of the workflow document:
https://github.com/geopython/pywps/blob/9fa56cc17bf545a9a583271d83affa5b479d3373/pywps/processing/job.py#L81

... and the json loader for the workflow document will fail.
https://github.com/roocs/rook/blob/858130631bf0a37c19a78e8e94961b7159846833/rook/processes/wps_orchestrate.py#L52

# Additional Information

PR #444

**Comment by cehbrecht** [comment]
@huard how would you handle this? 

Should we add the json data as it is without `CDATA`?
https://github.com/geopython/pywps/blob/9fa56cc17bf545a9a583271d83affa5b479d3373/pywps/inout/inputs.py#L227

Or when loading the json dump should the `CDATA` tag be removed?
https://github.com/geopython/pywps/blob/9fa56cc17bf545a9a583271d83affa5b479d3373/pywps/inout/inputs.py#L217

**Comment by huard** [comment]
Hi @cehbrecht , 

I remember banging my head about this, trying to find a solution that worked across the board. I think the issue is that the json content may contain characters that will confuse the xml parser, hence the need to put everything inside CDATA tags.

I thought that the XML parser removed the CDATA tags automatically. Sorry I don't have a better answer...

**Comment by cehbrecht** [comment]
fixed by #555
