### ISSUE TITLE
Download complex data and reference data

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#57]
<a href="https://github.com/jachym"><img src="https://avatars.githubusercontent.com/u/1460823?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jachym](https://github.com/jachym)**
_Saturday Apr 04, 2015 at 10:46 GMT_
_Originally opened as https://github.com/PyWPS/pywps-4/issues/48_

---

Download (and later validate) complex and reference data

https://github.com/jachym/pywps-4/blob/master/pywps/app.py#L55

**Comment by ldesousa** [comment]
This issue is no longer valid.
