### ISSUE TITLE
Unit mismatch in FileSizeExceeded error_message

### ISSUE THREAD

**Issue by huard** [geopython/pywps#571]
# Description

The `file` property of the `URLHandler` object checks if the data size is larger than the maximum data size. When it exceeds the maximum value, it raises an error: 
https://github.com/geopython/pywps/blob/20e1e254a3f7914e555fa89f363d1f6eb5f3895c/pywps/inout/basic.py#L458

The value is in units of bytes, but the message says megabytes. 

Also, it would be useful if the message included the actual size of the data. 

# Environment

- operating system:
- Python version: 3.8
- PyWPS version:4.2.9
- source/distribution
 - [x] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by huard** [comment]
Also, why is the FileSizeExceeded exception in the try statement replaced by NoApplicableCode?

**Comment by cehbrecht** [comment]
I run into the same issue:
https://github.com/roocs/rook/issues/139#issuecomment-797554832

**Comment by cehbrecht** [comment]
should be fixed by PRs #580 and #581.
