### ISSUE TITLE
Return lineage info (inputs) also with error response?

### ISSUE THREAD

**Issue by cehbrecht** [geopython/pywps#587]
# Description

In case of an error we would like to know the request. The wps has the `lineage` parameter to optionally return the inputs with a response document. Currently this happens only when the process was successful.

The [WPS 1.0.0 spec](https://www.ogc.org/standards/wps) says the following (p. 42):

> If lineage is ―true‖ (see Table 50), the Execute operation response shall include the DataInputs and OutputDefinitions elements. The server shall include in the execute response a complete copy of the DataInputs and OutputDefinition elements as received in the execute request. If lineage is "false" then these elements shall be omitted from the response.

# Environment

- operating system:
- Python version: 
- PyWPS version: 4.4.1
- source/distribution
 - [ ] git clone
 - [ ] Debian
 - [ ] PyPI
 - [ ] zip/tar.gz
 - [ ] other (please specify): 
- web server
 - [ ] Apache/mod_wsgi
 - [ ] CGI
 - [ ] other (please specify): 

# Steps to Reproduce

# Additional Information

**Comment by agstephens** [comment]
@cehbrecht this sounds like a useful addition.

**Comment by cehbrecht** [comment]
fixed by PR #589.
