### ISSUE TITLE
Scheduler and load balancer of processes

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#60]
<a href="https://github.com/jachym"><img src="https://avatars.githubusercontent.com/u/1460823?v=3" align="left" width="96" height="96" hspace="10"></img></a> **Issue by [jachym](https://github.com/jachym)**
_Thursday Sep 24, 2015 at 08:43 GMT_
_Originally opened as https://github.com/PyWPS/pywps-4/issues/68_

---

Scheduler of accepted processes and process queue.

Also balancer for horizontal scaling would be nice.

**Comment by ldesousa** [comment]
A scheduling mechanism was implemented by @cehbrecht on PR #296 
Enhancements related to process queuing are now merged into issue #237
