### ISSUE TITLE
Should `FileStorage.do_store` create the `outputpath` directory ?

### ISSUE THREAD

**Issue by huard** [geopython/pywps#635]
# Description

I'm a bit confused on whether or not PyWPS is expected to create the `outputpath` directory if it does not exist. 

The documentation says *server path where to store output files.*

If the directory does not exist, PyPWS fails in this call [here](https://github.com/geopython/pywps/blob/ced1484299761a834cc1cc854f4d9e9c2856e8b2/pywps/inout/storage/file.py#L85)
but it feels like this failure could be avoided by computing the free space on the drive where the target resides, or the *closest* existing parent directory.  Later in the code, `os.makedirs` is called, suggesting an intent to create recursively the target path. 

So it's not clear to me exactly what the desired behavior is. 

# Environment

- operating system: Ubuntu
- Python version: 3.9
- PyWPS version: 4.4

**Comment by tlvu** [comment]
Other than `server.outputpath`, there are 2 other directories in the `wps.cfg` config file: `server.workdir` and `server.temp_path` that will also need the dir to be created on service startup, if the dir do not already exist.

**Comment by cehbrecht** [comment]
In my deployments the Ansible playbook is creating the temp folders with correct permissions. So, the error was avoided. 

Would it help to run this code before `get_free_space(self.target)`?:
```
if not os.path.exists(self.target):
            os.makedirs(self.target)
```
