### ISSUE TITLE
setup demo instance

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#73]
It would be valuable to setup something like demo.pywps.org to provide a canonical demo based on master, etc. in support of OGC compliance and as we strive to become a reference implementation.

**Comment by tomkralidis** [comment]
I've setup demo.pycsw.org on the [OSGeo Adhoc VM](http://wiki.osgeo.org/wiki/AdhocVM):

- document root: `/osgeo/demo.pywps.org/www`
- Apache config `/etc/apache2/sites-available/demo.pycsw.org`

@jachym can you update the PyWPS DNS to add an A record called `demo` which points to `140.211.15.84`?

**Comment by jachym** [comment]
Oh yeah!

big thanks. demo.pywps.org is something, I was missing for quite a long time

I used pywps.cloudapp.net by microsoft, but was not sure, that will be
long-term sollution. osgeo servers would be much better

J

so 13. 2. 2016 v 23:19 odesílatel Tom Kralidis <notifications@github.com>
napsal:

**Comment by jachym** [comment]
Set, should work in any moment

ne 14. 2. 2016 v 9:14 odesílatel Jachym Cepicky <jachym.cepicky@gmail.com>
napsal:
