### ISSUE TITLE
update PyWPS Google+ presence

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#82]
Update [Google+](https://plus.google.com/communities/103965491493827721776) presence with the following updates:

- [x] logo should be new PyWPS logo
- [x] website should be http://pywps.org
- [x] description should be `PyWPS is an implementation of the Web Processing Service standard from the Open Geospatial Consortium. PyWPS is written in Python.` (as per https://github.com/geopython/pywps/wiki/Templates#project-description)

**Comment by tomkralidis** [comment]
cc @ldesousa

**Comment by ldesousa** [comment]
Done.
