### ISSUE TITLE
clarify contributors

### ISSUE THREAD

**Issue by tomkralidis** [geopython/pywps#84]
# Overview

There seem to be numerous places for documenting contributors:

1. http://pywps.org/contributors/
1. https://github.com/geopython/pywps/blob/master/CONTRIBUTORS.md
1. in the codebase in https://github.com/geopython/pywps.  Running `git log|grep "Author: "|sort -u` shows a historical list (some duplicates)

# Requirement

OSGeo Incubation will require us to get contributor agreements in place for present and past contributors to the project.  Sorting this out also makes good sense to reduce duplication and manage a central contribution manifest.

# Proposal

1. update http://pywps.org/contributors/#individuals to simply refer to https://github.com/geopython/pywps/blob/master/CONTRIBUTORS.md as the authoritative individual contributors list.  Everything else (i.e. Institutions) stays the same
1. update https://github.com/geopython/pywps/blob/master/CONTRIBUTORS.md to have a structured table of contributors past and present.  The list will be made up from grepping codebase git logs as well as https://github.com/geopython/pywps/graphs/contributors.  https://github.com/geopython/pywps/blob/master/CONTRIBUTORS.md will then also form the basis for gathering contribution agreements over time

**Comment by jachym** [comment]
Whoa, contribution agreements, I might know something about that :-/

Therefore, for PyWPS-4, the licence was always drawn to my person - so we can easily approach in the future.

The web page is there for slightly more personalised list (possibly with photos, like GRASS people have https://grasswiki.osgeo.org/wiki/Team - I love it)

**Comment by tomkralidis** [comment]
@jachym we have the option as part of incubation to transfer copyright to OSGeo proper.  Perhaps we should table with PSC?

**Comment by jachym** [comment]
IMHO that should go to PSC

po 29. 2. 2016 v 1:29 odesílatel Tom Kralidis <notifications@github.com>
napsal:

**Comment by jorgejesus** [comment]
I think this issue can be closed since authorship has been indicated in the new header of Pywps 4.0.0 and pywps 3.2.0  #187

**Comment by jachym** [comment]
Hi,
I suggest, we keep CONTRIBUTORS.md updated manually

 git shortlog -s -n

gives nice list, but confusing, due to svn -> git change

@tomkralidis ?

**Comment by tomkralidis** [comment]
+1 to keep manually and ensure new contributors are added over time/as required.

**Comment by jachym** [comment]
would this be ok @tomkralidis and @jorgejesus ? https://github.com/jachym/PyWPS/commit/38d754526229678c680b8016238b4dd934093275

**Comment by tomkralidis** [comment]
+1

**Comment by jorgejesus** [comment]
+1
Can do it manually

**Comment by jachym** [comment]
Fixing https://github.com/geopython/pywps/pull/199
Fixed http://pywps.org/contributors/

Closing
